/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  AddCarouselImagesList200Response,
  AddCarouselImagesListRequest,
  AddCollaborator201Response,
  CollabotatorRequest,
  CoverResponse,
  CreateScene400Response,
  CreateSceneRequest,
  DeleteUser200Response,
  EditCarouselImageList200Response,
  EditCarouselImageListRequest,
  EditSceneRequest,
  FavoriteListResponse,
  FavoriteSceneCrudRequest,
  FavouritesCrudRequest,
  FavouritesListResponse,
  GetUserInfoResponse,
  LikeSceneRequest,
  LikedScene200Response,
  ListCarouselImage400Response,
  ListCarouselImageResponse,
  ListCollaborators200Response,
  ListSceneHistroyResponse,
  ListScenesResponse,
  ListUserInfoResponse,
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  SceneResponse,
  UpdatePassword200Response,
  UpdatePasswordRequest,
  UpdateUserInfo200Response,
  UpdateUserInfoRequest,
  UploadAudio200Response,
  UploadCover400Response,
  UploadCoverRequest,
  UploadImageRequest,
  UploadImageResponse,
} from '../models/index'
import {
  AddCarouselImagesList200ResponseFromJSON,
  AddCarouselImagesList200ResponseToJSON,
  AddCarouselImagesListRequestFromJSON,
  AddCarouselImagesListRequestToJSON,
  AddCollaborator201ResponseFromJSON,
  AddCollaborator201ResponseToJSON,
  CollabotatorRequestFromJSON,
  CollabotatorRequestToJSON,
  CoverResponseFromJSON,
  CoverResponseToJSON,
  CreateScene400ResponseFromJSON,
  CreateScene400ResponseToJSON,
  CreateSceneRequestFromJSON,
  CreateSceneRequestToJSON,
  DeleteUser200ResponseFromJSON,
  DeleteUser200ResponseToJSON,
  EditCarouselImageList200ResponseFromJSON,
  EditCarouselImageList200ResponseToJSON,
  EditCarouselImageListRequestFromJSON,
  EditCarouselImageListRequestToJSON,
  EditSceneRequestFromJSON,
  EditSceneRequestToJSON,
  FavoriteListResponseFromJSON,
  FavoriteListResponseToJSON,
  FavoriteSceneCrudRequestFromJSON,
  FavoriteSceneCrudRequestToJSON,
  FavouritesCrudRequestFromJSON,
  FavouritesCrudRequestToJSON,
  FavouritesListResponseFromJSON,
  FavouritesListResponseToJSON,
  GetUserInfoResponseFromJSON,
  GetUserInfoResponseToJSON,
  LikeSceneRequestFromJSON,
  LikeSceneRequestToJSON,
  LikedScene200ResponseFromJSON,
  LikedScene200ResponseToJSON,
  ListCarouselImage400ResponseFromJSON,
  ListCarouselImage400ResponseToJSON,
  ListCarouselImageResponseFromJSON,
  ListCarouselImageResponseToJSON,
  ListCollaborators200ResponseFromJSON,
  ListCollaborators200ResponseToJSON,
  ListSceneHistroyResponseFromJSON,
  ListSceneHistroyResponseToJSON,
  ListScenesResponseFromJSON,
  ListScenesResponseToJSON,
  ListUserInfoResponseFromJSON,
  ListUserInfoResponseToJSON,
  LoginRequestFromJSON,
  LoginRequestToJSON,
  LoginResponseFromJSON,
  LoginResponseToJSON,
  RegisterRequestFromJSON,
  RegisterRequestToJSON,
  SceneResponseFromJSON,
  SceneResponseToJSON,
  UpdatePassword200ResponseFromJSON,
  UpdatePassword200ResponseToJSON,
  UpdatePasswordRequestFromJSON,
  UpdatePasswordRequestToJSON,
  UpdateUserInfo200ResponseFromJSON,
  UpdateUserInfo200ResponseToJSON,
  UpdateUserInfoRequestFromJSON,
  UpdateUserInfoRequestToJSON,
  UploadAudio200ResponseFromJSON,
  UploadAudio200ResponseToJSON,
  UploadCover400ResponseFromJSON,
  UploadCover400ResponseToJSON,
  UploadCoverRequestFromJSON,
  UploadCoverRequestToJSON,
  UploadImageRequestFromJSON,
  UploadImageRequestToJSON,
  UploadImageResponseFromJSON,
  UploadImageResponseToJSON,
} from '../models/index'

export interface AddCarouselImagesListOperationRequest {
  addCarouselImagesListRequest?: AddCarouselImagesListRequest
}

export interface AddCollaboratorRequest {
  collabotatorRequest?: CollabotatorRequest
}

export interface CommandRequest {
  command?: string
}

export interface CreateSceneOperationRequest {
  createSceneRequest?: CreateSceneRequest
}

export interface DeleteCarouselImageListRequest {
  carouselImageId: number
}

export interface DeleteSceneRequest {
  id: number
}

export interface DeleteUserRequest {
  body?: object
}

export interface EditCarouselImageListOperationRequest {
  editCarouselImageListRequest?: EditCarouselImageListRequest
}

export interface EditSceneOperationRequest {
  editSceneRequest?: EditSceneRequest
}

export interface FavoriteCRUDRequest {
  favoriteSceneCrudRequest?: FavoriteSceneCrudRequest
}

export interface FavouritesCRUDRequest {
  favouritesCrudRequest?: FavouritesCrudRequest
}

export interface GetSceneRequest {
  id: number
}

export interface GetSceneCoverRequest {
  sceneId: number
}

export interface GetUserInfoRequest {
  id?: number
}

export interface GetUserListByNameRequest {
  name?: string
}

export interface GetUserSceneHistoryRequest {
  first?: number
  after?: number
}

export interface LikedSceneRequest {
  likeSceneRequest?: LikeSceneRequest
}

export interface ListCarouselImageRequest {
  first?: number
  after?: number
}

export interface ListCollaboratorsRequest {
  sceneId: number
}

export interface ListSceneRequest {
  first?: number
  after?: number
  userId?: number
  keyword?: string
  isRecycleBin?: number
  publicMode?: boolean
  tag?: string
}

export interface LoginOperationRequest {
  loginRequest?: LoginRequest
}

export interface RecommendSceneRequest {
  recommendType: RecommendSceneRecommendTypeV4Compat
  sceneId?: number
}

export interface RegisterOperationRequest {
  registerRequest?: RegisterRequest
}

export interface RemoveCollaboratorRequest {
  collabotatorRequest?: CollabotatorRequest
}

export interface UndoDeleteSceneRequest {
  id: number
}

export interface UpdatePasswordOperationRequest {
  updatePasswordRequest?: UpdatePasswordRequest
}

export interface UpdateUserInfoOperationRequest {
  updateUserInfoRequest?: UpdateUserInfoRequest
}

export interface UploadAudioRequest {
  audioFile?: Blob
}

export interface UploadCoverOperationRequest {
  uploadCoverRequest?: UploadCoverRequest
}

export interface UploadImageOperationRequest {
  uploadImageRequest?: UploadImageRequest
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   *
   * 添加轮播图列表
   */
  async addCarouselImagesListRaw(
    requestParameters: AddCarouselImagesListOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddCarouselImagesList200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/carousel/add`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: AddCarouselImagesListRequestToJSON(requestParameters['addCarouselImagesListRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AddCarouselImagesList200ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 添加轮播图列表
   */
  async addCarouselImagesList(
    addCarouselImagesListRequest?: AddCarouselImagesListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddCarouselImagesList200Response> {
    const response = await this.addCarouselImagesListRaw(
      { addCarouselImagesListRequest: addCarouselImagesListRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 当数据库中已有历史映射时，返回用户名已存在异常 补充说明：该接口有个潜在bug还没修，即当添加的协助者id就是场景创建者时，应该做对应的处理，否则同场景列表接口可能出现错误交互（比如返回重复场景）
   * 添加场景协作者
   * @deprecated
   */
  async addCollaboratorRaw(
    requestParameters: AddCollaboratorRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddCollaborator201Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/collaborator/add`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: CollabotatorRequestToJSON(requestParameters['collabotatorRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AddCollaborator201ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 当数据库中已有历史映射时，返回用户名已存在异常 补充说明：该接口有个潜在bug还没修，即当添加的协助者id就是场景创建者时，应该做对应的处理，否则同场景列表接口可能出现错误交互（比如返回重复场景）
   * 添加场景协作者
   * @deprecated
   */
  async addCollaborator(
    collabotatorRequest?: CollabotatorRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddCollaborator201Response> {
    const response = await this.addCollaboratorRaw(
      { collabotatorRequest: collabotatorRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 用于在服务器上手动执行一些命令，比如手动初始化ES索引表，手动更新ES文档等 内部对userId对应用户的role做鉴定，如果不是管理员，返回无权限异常 当前支持的命令： es init user index es update user doc es init scene index es update scene doc clean cache images calculate recommend dat
   * 命令行接口
   */
  async commandRaw(
    requestParameters: CommandRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    const queryParameters: any = {}

    if (requestParameters['command'] != null) {
      queryParameters['command'] = requestParameters['command']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/general/command`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * 用于在服务器上手动执行一些命令，比如手动初始化ES索引表，手动更新ES文档等 内部对userId对应用户的role做鉴定，如果不是管理员，返回无权限异常 当前支持的命令： es init user index es update user doc es init scene index es update scene doc clean cache images calculate recommend dat
   * 命令行接口
   */
  async command(
    command?: string,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.commandRaw({ command: command }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 创建场景
   */
  async createSceneRaw(
    requestParameters: CreateSceneOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SceneResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/create`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: CreateSceneRequestToJSON(requestParameters['createSceneRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => SceneResponseFromJSON(jsonValue))
  }

  /**
   *
   * 创建场景
   */
  async createScene(
    createSceneRequest?: CreateSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SceneResponse> {
    const response = await this.createSceneRaw(
      { createSceneRequest: createSceneRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 删除轮播图列表
   */
  async deleteCarouselImageListRaw(
    requestParameters: DeleteCarouselImageListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters['carouselImageId'] == null) {
      throw new runtime.RequiredError(
        'carouselImageId',
        'Required parameter "carouselImageId" was null or undefined when calling deleteCarouselImageList().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['carouselImageId'] != null) {
      queryParameters['carouselImageId'] = requestParameters['carouselImageId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/carousel/delete`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   *
   * 删除轮播图列表
   */
  async deleteCarouselImageList(
    carouselImageId: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.deleteCarouselImageListRaw(
      { carouselImageId: carouselImageId },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 删除场景
   */
  async deleteSceneRaw(
    requestParameters: DeleteSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteScene().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['id'] != null) {
      queryParameters['id'] = requestParameters['id']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   *
   * 删除场景
   */
  async deleteScene(
    id: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.deleteSceneRaw({ id: id }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 删除用户
   */
  async deleteUserRaw(
    requestParameters: DeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DeleteUser200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/delete`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['body'] as any,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeleteUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 删除用户
   */
  async deleteUser(
    body?: object,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DeleteUser200Response> {
    const response = await this.deleteUserRaw({ body: body }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 修改轮播图列表
   */
  async editCarouselImageListRaw(
    requestParameters: EditCarouselImageListOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EditCarouselImageList200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/carousel/edit`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: EditCarouselImageListRequestToJSON(requestParameters['editCarouselImageListRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EditCarouselImageList200ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 修改轮播图列表
   */
  async editCarouselImageList(
    editCarouselImageListRequest?: EditCarouselImageListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EditCarouselImageList200Response> {
    const response = await this.editCarouselImageListRaw(
      { editCarouselImageListRequest: editCarouselImageListRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * “tag”和“协作者”需要每次修改传回所有数据更新，birthPosition和birthRotation同理 (即想删除/修改“tag”和“协作者”只需要把修改后的结果传回来，进行更新即可
   * 修改场景
   */
  async editSceneRaw(
    requestParameters: EditSceneOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SceneResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/edit`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: EditSceneRequestToJSON(requestParameters['editSceneRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => SceneResponseFromJSON(jsonValue))
  }

  /**
   * “tag”和“协作者”需要每次修改传回所有数据更新，birthPosition和birthRotation同理 (即想删除/修改“tag”和“协作者”只需要把修改后的结果传回来，进行更新即可
   * 修改场景
   */
  async editScene(
    editSceneRequest?: EditSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SceneResponse> {
    const response = await this.editSceneRaw({ editSceneRequest: editSceneRequest }, initOverrides)
    return await response.value()
  }

  /**
   * create:添加新的收藏场景 read:列出所有收藏场景 update:用新的sceneId数组覆写旧的,参考修改协助者列表 delete:删除收藏场景
   * 收藏场景增删查改
   */
  async favoriteCRUDRaw(
    requestParameters: FavoriteCRUDRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FavoriteListResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/favourites/favorite/crud`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['favoriteSceneCrudRequest'],
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FavoriteListResponseFromJSON(jsonValue),
    )
  }

  /**
   * create:添加新的收藏场景 read:列出所有收藏场景 update:用新的sceneId数组覆写旧的,参考修改协助者列表 delete:删除收藏场景
   * 收藏场景增删查改
   */
  async favoriteCRUD(
    favoriteSceneCrudRequest?: FavoriteSceneCrudRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FavoriteListResponse> {
    const response = await this.favoriteCRUDRaw(
      { favoriteSceneCrudRequest: favoriteSceneCrudRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 收藏夹crud create:创建新的收藏夹，需要收藏夹名称 read:列出所有收藏夹，总是包含default，不需要参数 update:修改收藏夹，需要目标收藏夹名称以及修改后的新的收藏夹名称，目标收藏夹名称不应该是default delete:删除目标收藏夹，default不可删除 将校验operation同body是否匹配，包括operation==read时，要求body为空，body:{}
   * 收藏夹增删查改
   */
  async favouritesCRUDRaw(
    requestParameters: FavouritesCRUDRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FavouritesListResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/favourites/crud`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['favouritesCrudRequest'],
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FavouritesListResponseFromJSON(jsonValue),
    )
  }

  /**
   * 收藏夹crud create:创建新的收藏夹，需要收藏夹名称 read:列出所有收藏夹，总是包含default，不需要参数 update:修改收藏夹，需要目标收藏夹名称以及修改后的新的收藏夹名称，目标收藏夹名称不应该是default delete:删除目标收藏夹，default不可删除 将校验operation同body是否匹配，包括operation==read时，要求body为空，body:{}
   * 收藏夹增删查改
   */
  async favouritesCRUD(
    favouritesCrudRequest?: FavouritesCrudRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FavouritesListResponse> {
    const response = await this.favouritesCRUDRaw(
      { favouritesCrudRequest: favouritesCrudRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 获取场景信息
   */
  async getSceneRaw(
    requestParameters: GetSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SceneResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getScene().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['id'] != null) {
      queryParameters['id'] = requestParameters['id']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => SceneResponseFromJSON(jsonValue))
  }

  /**
   *
   * 获取场景信息
   */
  async getScene(
    id: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SceneResponse> {
    const response = await this.getSceneRaw({ id: id }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 获取封面
   * @deprecated
   */
  async getSceneCoverRaw(
    requestParameters: GetSceneCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CoverResponse>> {
    if (requestParameters['sceneId'] == null) {
      throw new runtime.RequiredError(
        'sceneId',
        'Required parameter "sceneId" was null or undefined when calling getSceneCover().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['sceneId'] != null) {
      queryParameters['sceneId'] = requestParameters['sceneId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/cover`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => CoverResponseFromJSON(jsonValue))
  }

  /**
   *
   * 获取封面
   * @deprecated
   */
  async getSceneCover(
    sceneId: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CoverResponse> {
    const response = await this.getSceneCoverRaw({ sceneId: sceneId }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 根据 ID 查询用户信息
   */
  async getUserInfoRaw(
    requestParameters: GetUserInfoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUserInfoResponse>> {
    const queryParameters: any = {}

    if (requestParameters['id'] != null) {
      queryParameters['id'] = requestParameters['id']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/info`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUserInfoResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 根据 ID 查询用户信息
   */
  async getUserInfo(
    id?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUserInfoResponse> {
    const response = await this.getUserInfoRaw({ id: id }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 名字查询用户信息
   */
  async getUserListByNameRaw(
    requestParameters: GetUserListByNameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListUserInfoResponse>> {
    const queryParameters: any = {}

    if (requestParameters['name'] != null) {
      queryParameters['name'] = requestParameters['name']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/infoByName`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListUserInfoResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 名字查询用户信息
   */
  async getUserListByName(
    name?: string,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListUserInfoResponse> {
    const response = await this.getUserListByNameRaw({ name: name }, initOverrides)
    return await response.value()
  }

  /**
   * 获取当前用户记录 前50条从Redis获取，但是返回结果可能会多于50条，因为每晚0点才把redis刷入mysql 负数表示从Redis中获取的数据 如果返回结果以正数开头的话，表明采取了服务降级
   * 获取用户浏览历史
   */
  async getUserSceneHistoryRaw(
    requestParameters: GetUserSceneHistoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListSceneHistroyResponse>> {
    const queryParameters: any = {}

    if (requestParameters['first'] != null) {
      queryParameters['first'] = requestParameters['first']
    }

    if (requestParameters['after'] != null) {
      queryParameters['after'] = requestParameters['after']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/scene/history`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListSceneHistroyResponseFromJSON(jsonValue),
    )
  }

  /**
   * 获取当前用户记录 前50条从Redis获取，但是返回结果可能会多于50条，因为每晚0点才把redis刷入mysql 负数表示从Redis中获取的数据 如果返回结果以正数开头的话，表明采取了服务降级
   * 获取用户浏览历史
   */
  async getUserSceneHistory(
    first?: number,
    after?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListSceneHistroyResponse> {
    const response = await this.getUserSceneHistoryRaw(
      { first: first, after: after },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 获取点赞信息
   */
  async likedSceneRaw(
    requestParameters: LikedSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LikedScene200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/like`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: LikeSceneRequestToJSON(requestParameters['likeSceneRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LikedScene200ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 获取点赞信息
   */
  async likedScene(
    likeSceneRequest?: LikeSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LikedScene200Response> {
    const response = await this.likedSceneRaw({ likeSceneRequest: likeSceneRequest }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 获取轮播图列表
   */
  async listCarouselImageRaw(
    requestParameters: ListCarouselImageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListCarouselImageResponse>> {
    const queryParameters: any = {}

    if (requestParameters['first'] != null) {
      queryParameters['first'] = requestParameters['first']
    }

    if (requestParameters['after'] != null) {
      queryParameters['after'] = requestParameters['after']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/carousel/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListCarouselImageResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 获取轮播图列表
   */
  async listCarouselImage(
    first?: number,
    after?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListCarouselImageResponse> {
    const response = await this.listCarouselImageRaw({ first: first, after: after }, initOverrides)
    return await response.value()
  }

  /**
   * 应该将该接口合并到获取场景信息接口中 获取场景信息接口应该提供协助者ID列表
   * 获取协助者列表
   * @deprecated
   */
  async listCollaboratorsRaw(
    requestParameters: ListCollaboratorsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListCollaborators200Response>> {
    if (requestParameters['sceneId'] == null) {
      throw new runtime.RequiredError(
        'sceneId',
        'Required parameter "sceneId" was null or undefined when calling listCollaborators().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['sceneId'] != null) {
      queryParameters['sceneId'] = requestParameters['sceneId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/collaborator/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListCollaborators200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 应该将该接口合并到获取场景信息接口中 获取场景信息接口应该提供协助者ID列表
   * 获取协助者列表
   * @deprecated
   */
  async listCollaborators(
    sceneId: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListCollaborators200Response> {
    const response = await this.listCollaboratorsRaw({ sceneId: sceneId }, initOverrides)
    return await response.value()
  }

  /**
   * 当不传入user_id时，获取所有公开场景 当传入user_id时，如果user_id==当前用户id，获取公开的和私有的场景，一并返回协作者场景 否则不返回协作者场景，并且只获取user_id的公开场景 获取回收站场景列表需要传入userid，参数isRecycleBin设为1
   * 获取场景列表
   */
  async listSceneRaw(
    requestParameters: ListSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListScenesResponse>> {
    const queryParameters: any = {}

    if (requestParameters['first'] != null) {
      queryParameters['first'] = requestParameters['first']
    }

    if (requestParameters['after'] != null) {
      queryParameters['after'] = requestParameters['after']
    }

    if (requestParameters['userId'] != null) {
      queryParameters['user_id'] = requestParameters['userId']
    }

    if (requestParameters['keyword'] != null) {
      queryParameters['keyword'] = requestParameters['keyword']
    }

    if (requestParameters['isRecycleBin'] != null) {
      queryParameters['isRecycleBin'] = requestParameters['isRecycleBin']
    }

    if (requestParameters['publicMode'] != null) {
      queryParameters['publicMode'] = requestParameters['publicMode']
    }

    if (requestParameters['tag'] != null) {
      queryParameters['tag'] = requestParameters['tag']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListScenesResponseFromJSON(jsonValue),
    )
  }

  /**
   * 当不传入user_id时，获取所有公开场景 当传入user_id时，如果user_id==当前用户id，获取公开的和私有的场景，一并返回协作者场景 否则不返回协作者场景，并且只获取user_id的公开场景 获取回收站场景列表需要传入userid，参数isRecycleBin设为1
   * 获取场景列表
   */
  async listScene(
    first?: number,
    after?: number,
    userId?: number,
    keyword?: string,
    isRecycleBin?: number,
    publicMode?: boolean,
    tag?: string,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListScenesResponse> {
    const response = await this.listSceneRaw(
      {
        first: first,
        after: after,
        userId: userId,
        keyword: keyword,
        isRecycleBin: isRecycleBin,
        publicMode: publicMode,
        tag: tag,
      },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 用户登录
   */
  async loginRaw(
    requestParameters: LoginOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/user/login`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: LoginRequestToJSON(requestParameters['loginRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue))
  }

  /**
   *
   * 用户登录
   */
  async login(
    loginRequest?: LoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LoginResponse> {
    const response = await this.loginRaw({ loginRequest: loginRequest }, initOverrides)
    return await response.value()
  }

  /**
   * 返回推荐的场景列表 分为基于用户和基于物品 当没有合适的推荐对象时，返回最受欢迎的物品 总是推荐6个
   * 推荐场景
   */
  async recommendSceneRaw(
    requestParameters: RecommendSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListScenesResponse>> {
    if (requestParameters['recommendType'] == null) {
      throw new runtime.RequiredError(
        'recommendType',
        'Required parameter "recommendType" was null or undefined when calling recommendScene().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['recommendType'] != null) {
      queryParameters['recommendType'] = requestParameters['recommendType']
    }

    if (requestParameters['sceneId'] != null) {
      queryParameters['sceneId'] = requestParameters['sceneId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/recommend`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListScenesResponseFromJSON(jsonValue),
    )
  }

  /**
   * 返回推荐的场景列表 分为基于用户和基于物品 当没有合适的推荐对象时，返回最受欢迎的物品 总是推荐6个
   * 推荐场景
   */
  async recommendScene(
    recommendType: RecommendSceneRecommendTypeV4Compat,
    sceneId?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListScenesResponse> {
    const response = await this.recommendSceneRaw(
      { recommendType: recommendType, sceneId: sceneId },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 用户注册
   */
  async registerRaw(
    requestParameters: RegisterOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/user/register`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RegisterRequestToJSON(requestParameters['registerRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   *
   * 用户注册
   */
  async register(
    registerRequest?: RegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.registerRaw({ registerRequest: registerRequest }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 移除场景协作者
   * @deprecated
   */
  async removeCollaboratorRaw(
    requestParameters: RemoveCollaboratorRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddCollaborator201Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/collaborator/remove`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CollabotatorRequestToJSON(requestParameters['collabotatorRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AddCollaborator201ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 移除场景协作者
   * @deprecated
   */
  async removeCollaborator(
    collabotatorRequest?: CollabotatorRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddCollaborator201Response> {
    const response = await this.removeCollaboratorRaw(
      { collabotatorRequest: collabotatorRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 撤销删除场景
   */
  async undoDeleteSceneRaw(
    requestParameters: UndoDeleteSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling undoDeleteScene().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['id'] != null) {
      queryParameters['id'] = requestParameters['id']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/delete/undo`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   *
   * 撤销删除场景
   */
  async undoDeleteScene(
    id: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.undoDeleteSceneRaw({ id: id }, initOverrides)
    return await response.value()
  }

  /**
   * ### 修改密码会产生新的Token
   * 修改密码
   */
  async updatePasswordRaw(
    requestParameters: UpdatePasswordOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdatePassword200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/User/updatePassword`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: UpdatePasswordRequestToJSON(requestParameters['updatePasswordRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdatePassword200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * ### 修改密码会产生新的Token
   * 修改密码
   */
  async updatePassword(
    updatePasswordRequest?: UpdatePasswordRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdatePassword200Response> {
    const response = await this.updatePasswordRaw(
      { updatePasswordRequest: updatePasswordRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 目前支持修改头像，用户名，昵称，签名，性别，生日，地址，置顶场景 置顶场景：限制3个，并且置顶场景只涉及覆盖操作，若为空表示不做修改 日期要求参数字符串格式 “YYYY-MM-DD” 后续可以添加
   * 更新用户信息
   */
  async updateUserInfoRaw(
    requestParameters: UpdateUserInfoOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdateUserInfo200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/updateInfo`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateUserInfoRequestToJSON(requestParameters['updateUserInfoRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdateUserInfo200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 目前支持修改头像，用户名，昵称，签名，性别，生日，地址，置顶场景 置顶场景：限制3个，并且置顶场景只涉及覆盖操作，若为空表示不做修改 日期要求参数字符串格式 “YYYY-MM-DD” 后续可以添加
   * 更新用户信息
   */
  async updateUserInfo(
    updateUserInfoRequest?: UpdateUserInfoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdateUserInfo200Response> {
    const response = await this.updateUserInfoRaw(
      { updateUserInfoRequest: updateUserInfoRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * #### 要求限制音频大小20MB以内，目前限制格式为MP3，建议在前端写明
   * 上传音频
   */
  async uploadAudioRaw(
    requestParameters: UploadAudioRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UploadAudio200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const consumes: runtime.Consume[] = [{ contentType: 'multipart/form-data' }]
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes)

    let formParams: { append(param: string, value: any): any }
    let useForm = false
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm
    if (useForm) {
      formParams = new FormData()
    } else {
      formParams = new URLSearchParams()
    }

    if (requestParameters['audioFile'] != null) {
      formParams.append('audioFile', requestParameters['audioFile'] as any)
    }

    const response = await this.request(
      {
        path: `/general/upload/audio`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UploadAudio200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * #### 要求限制音频大小20MB以内，目前限制格式为MP3，建议在前端写明
   * 上传音频
   */
  async uploadAudio(
    audioFile?: Blob,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UploadAudio200Response> {
    const response = await this.uploadAudioRaw({ audioFile: audioFile }, initOverrides)
    return await response.value()
  }

  /**
   * 上传封面图片到腾讯云对象存储 上传到/scene/{{sceneId}}/cover.jpg 当从token中解析出来的用户ID不是场景创建或协作者者时，返回无权限异常 审核失败时，也返回400无法解析图片异常 补充说明：后端有个测试可以跑，见sceneApiControllerTest中的testUploadCover方法，把group.jpg替换成你想要上传的图片文件，访问测试返回响应中的url就能下载图片文件（可能有点延迟）
   * 上传封面
   * @deprecated
   */
  async uploadCoverRaw(
    requestParameters: UploadCoverOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CoverResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/cover/upload`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UploadCoverRequestToJSON(requestParameters['uploadCoverRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => CoverResponseFromJSON(jsonValue))
  }

  /**
   * 上传封面图片到腾讯云对象存储 上传到/scene/{{sceneId}}/cover.jpg 当从token中解析出来的用户ID不是场景创建或协作者者时，返回无权限异常 审核失败时，也返回400无法解析图片异常 补充说明：后端有个测试可以跑，见sceneApiControllerTest中的testUploadCover方法，把group.jpg替换成你想要上传的图片文件，访问测试返回响应中的url就能下载图片文件（可能有点延迟）
   * 上传封面
   * @deprecated
   */
  async uploadCover(
    uploadCoverRequest?: UploadCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CoverResponse> {
    const response = await this.uploadCoverRaw(
      { uploadCoverRequest: uploadCoverRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * ##### 上传图片 ###### 有场景封面，头像，介绍点图片 ###### type:{sceneCover, avatar, introduction}
   * 上传图片
   */
  async uploadImageRaw(
    requestParameters: UploadImageOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UploadImageResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/general/upload/image`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: UploadImageRequestToJSON(requestParameters['uploadImageRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UploadImageResponseFromJSON(jsonValue),
    )
  }

  /**
   * ##### 上传图片 ###### 有场景封面，头像，介绍点图片 ###### type:{sceneCover, avatar, introduction}
   * 上传图片
   */
  async uploadImage(
    uploadImageRequest?: UploadImageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UploadImageResponse> {
    const response = await this.uploadImageRaw(
      { uploadImageRequest: uploadImageRequest },
      initOverrides,
    )
    return await response.value()
  }
}

/**
 * @export
 */
export const RecommendSceneRecommendTypeV4Compat = {
  UserBasedRecommend: 'userBasedRecommend',
  ItemBasedRecommend: 'itemBasedRecommend',
} as const
export type RecommendSceneRecommendTypeV4Compat =
  (typeof RecommendSceneRecommendTypeV4Compat)[keyof typeof RecommendSceneRecommendTypeV4Compat]
