/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  CreateScene400Response,
  UploadAudio200Response,
  UploadCover400Response,
  UploadImageRequest,
  UploadImageResponse,
} from '../models/index'
import {
  CreateScene400ResponseFromJSON,
  CreateScene400ResponseToJSON,
  UploadAudio200ResponseFromJSON,
  UploadAudio200ResponseToJSON,
  UploadCover400ResponseFromJSON,
  UploadCover400ResponseToJSON,
  UploadImageRequestFromJSON,
  UploadImageRequestToJSON,
  UploadImageResponseFromJSON,
  UploadImageResponseToJSON,
} from '../models/index'

export interface CommandRequest {
  command?: string
}

export interface UploadAudioRequest {
  audioFile?: Blob
}

export interface UploadImageOperationRequest {
  uploadImageRequest?: UploadImageRequest
}

/**
 *
 */
export class GeneralApi extends runtime.BaseAPI {
  /**
   * 用于在服务器上手动执行一些命令，比如手动初始化ES索引表，手动更新ES文档等 内部对userId对应用户的role做鉴定，如果不是管理员，返回无权限异常 当前支持的命令： es init user index es update user doc es init scene index es update scene doc clean cache images calculate recommend dat
   * 命令行接口
   */
  async commandRaw(
    requestParameters: CommandRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    const queryParameters: any = {}

    if (requestParameters['command'] != null) {
      queryParameters['command'] = requestParameters['command']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/general/command`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * 用于在服务器上手动执行一些命令，比如手动初始化ES索引表，手动更新ES文档等 内部对userId对应用户的role做鉴定，如果不是管理员，返回无权限异常 当前支持的命令： es init user index es update user doc es init scene index es update scene doc clean cache images calculate recommend dat
   * 命令行接口
   */
  async command(
    command?: string,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.commandRaw({ command: command }, initOverrides)
    return await response.value()
  }

  /**
   * #### 要求限制音频大小20MB以内，目前限制格式为MP3，建议在前端写明
   * 上传音频
   */
  async uploadAudioRaw(
    requestParameters: UploadAudioRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UploadAudio200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const consumes: runtime.Consume[] = [{ contentType: 'multipart/form-data' }]
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes)

    let formParams: { append(param: string, value: any): any }
    let useForm = false
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm
    if (useForm) {
      formParams = new FormData()
    } else {
      formParams = new URLSearchParams()
    }

    if (requestParameters['audioFile'] != null) {
      formParams.append('audioFile', requestParameters['audioFile'] as any)
    }

    const response = await this.request(
      {
        path: `/general/upload/audio`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UploadAudio200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * #### 要求限制音频大小20MB以内，目前限制格式为MP3，建议在前端写明
   * 上传音频
   */
  async uploadAudio(
    audioFile?: Blob,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UploadAudio200Response> {
    const response = await this.uploadAudioRaw({ audioFile: audioFile }, initOverrides)
    return await response.value()
  }

  /**
   * ##### 上传图片 ###### 有场景封面，头像，介绍点图片 ###### type:{sceneCover, avatar, introduction}
   * 上传图片
   */
  async uploadImageRaw(
    requestParameters: UploadImageOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UploadImageResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/general/upload/image`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: UploadImageRequestToJSON(requestParameters['uploadImageRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UploadImageResponseFromJSON(jsonValue),
    )
  }

  /**
   * ##### 上传图片 ###### 有场景封面，头像，介绍点图片 ###### type:{sceneCover, avatar, introduction}
   * 上传图片
   */
  async uploadImage(
    uploadImageRequest?: UploadImageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UploadImageResponse> {
    const response = await this.uploadImageRaw(
      { uploadImageRequest: uploadImageRequest },
      initOverrides,
    )
    return await response.value()
  }
}
