/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  AddAnnotationRequest,
  AddCarouselImagesList200Response,
  AddCarouselImagesListRequest,
  AddCollaborator201Response,
  AddTagList200Response,
  AddTagListRequest,
  AnnotationResponse,
  CollabotatorRequest,
  CoverResponse,
  CreateScene400Response,
  CreateSceneRequest,
  DeleteTagListRequest,
  EditAnnotationRequest1,
  EditCarouselImageList200Response,
  EditCarouselImageListRequest,
  EditSceneRequest,
  GetTagListByName200Response,
  LikeSceneRequest,
  LikedScene200Response,
  ListAnnotationResponse,
  ListCarouselImage400Response,
  ListCarouselImageResponse,
  ListCollaborators200Response,
  ListScenesResponse,
  OrderAnnotationRequest,
  SceneResponse,
  UploadCover400Response,
  UploadCoverRequest,
  UploadIntroductionImage200Response,
  UploadVideo200Response,
} from '../models/index'
import {
  AddAnnotationRequestFromJSON,
  AddAnnotationRequestToJSON,
  AddCarouselImagesList200ResponseFromJSON,
  AddCarouselImagesList200ResponseToJSON,
  AddCarouselImagesListRequestFromJSON,
  AddCarouselImagesListRequestToJSON,
  AddCollaborator201ResponseFromJSON,
  AddCollaborator201ResponseToJSON,
  AddTagList200ResponseFromJSON,
  AddTagList200ResponseToJSON,
  AddTagListRequestFromJSON,
  AddTagListRequestToJSON,
  AnnotationResponseFromJSON,
  AnnotationResponseToJSON,
  CollabotatorRequestFromJSON,
  CollabotatorRequestToJSON,
  CoverResponseFromJSON,
  CoverResponseToJSON,
  CreateScene400ResponseFromJSON,
  CreateScene400ResponseToJSON,
  CreateSceneRequestFromJSON,
  CreateSceneRequestToJSON,
  DeleteTagListRequestFromJSON,
  DeleteTagListRequestToJSON,
  EditAnnotationRequest1FromJSON,
  EditAnnotationRequest1ToJSON,
  EditCarouselImageList200ResponseFromJSON,
  EditCarouselImageList200ResponseToJSON,
  EditCarouselImageListRequestFromJSON,
  EditCarouselImageListRequestToJSON,
  EditSceneRequestFromJSON,
  EditSceneRequestToJSON,
  GetTagListByName200ResponseFromJSON,
  GetTagListByName200ResponseToJSON,
  LikeSceneRequestFromJSON,
  LikeSceneRequestToJSON,
  LikedScene200ResponseFromJSON,
  LikedScene200ResponseToJSON,
  ListAnnotationResponseFromJSON,
  ListAnnotationResponseToJSON,
  ListCarouselImage400ResponseFromJSON,
  ListCarouselImage400ResponseToJSON,
  ListCarouselImageResponseFromJSON,
  ListCarouselImageResponseToJSON,
  ListCollaborators200ResponseFromJSON,
  ListCollaborators200ResponseToJSON,
  ListScenesResponseFromJSON,
  ListScenesResponseToJSON,
  OrderAnnotationRequestFromJSON,
  OrderAnnotationRequestToJSON,
  SceneResponseFromJSON,
  SceneResponseToJSON,
  UploadCover400ResponseFromJSON,
  UploadCover400ResponseToJSON,
  UploadCoverRequestFromJSON,
  UploadCoverRequestToJSON,
  UploadIntroductionImage200ResponseFromJSON,
  UploadIntroductionImage200ResponseToJSON,
  UploadVideo200ResponseFromJSON,
  UploadVideo200ResponseToJSON,
} from '../models/index'

export interface AddAnnotationOperationRequest {
  addAnnotationRequest?: AddAnnotationRequest
}

export interface AddCarouselImagesListOperationRequest {
  addCarouselImagesListRequest?: AddCarouselImagesListRequest
}

export interface AddCollaboratorRequest {
  collabotatorRequest?: CollabotatorRequest
}

export interface AddTagListOperationRequest {
  addTagListRequest?: AddTagListRequest
}

export interface CreateSceneOperationRequest {
  createSceneRequest?: CreateSceneRequest
}

export interface DeleteSceneRequest {
  id: number
}

export interface DeleteTagListOperationRequest {
  deleteTagListRequest?: DeleteTagListRequest
}

export interface EditAnnotationRequest {
  editAnnotationRequest1?: EditAnnotationRequest1
}

export interface EditCarouselImageListOperationRequest {
  editCarouselImageListRequest?: EditCarouselImageListRequest
}

export interface EditSceneOperationRequest {
  editSceneRequest?: EditSceneRequest
}

export interface GetAnnotationDetailsRequest {
  annotationId: number
}

export interface GetSceneRequest {
  id: number
}

export interface GetSceneCoverRequest {
  sceneId: number
}

export interface GetTagListByNameRequest {
  tagName: string
}

export interface LikedSceneRequest {
  likeSceneRequest?: LikeSceneRequest
}

export interface ListAnnotationRequest {
  sceneId: number
}

export interface ListCarouselImageRequest {
  first?: number
  after?: number
}

export interface ListCollaboratorsRequest {
  sceneId: number
}

export interface ListSceneRequest {
  first?: number
  after?: number
  userId?: number
  keyword?: string
  isRecycleBin?: number
  publicMode?: boolean
  tag?: string
}

export interface OrderAnnotationOperationRequest {
  orderAnnotationRequest?: OrderAnnotationRequest
}

export interface RemoveAnnotationRequest {
  annotationId?: number
}

export interface RemoveCollaboratorRequest {
  collabotatorRequest?: CollabotatorRequest
}

export interface UndoDeleteSceneRequest {
  id: number
}

export interface UploadCoverOperationRequest {
  uploadCoverRequest?: UploadCoverRequest
}

export interface UploadIntroductionImageRequest {
  jpgFile: Blob
}

export interface UploadVideoRequest {
  videoFile: Blob
}

/**
 *
 */
export class SceneApi extends runtime.BaseAPI {
  /**
   * 非场景管理员在发送添加场景标记请求时，应该返回无权限异常。
   * 创建标记
   */
  async addAnnotationRaw(
    requestParameters: AddAnnotationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AnnotationResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/annotation/add`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: AddAnnotationRequestToJSON(requestParameters['addAnnotationRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AnnotationResponseFromJSON(jsonValue),
    )
  }

  /**
   * 非场景管理员在发送添加场景标记请求时，应该返回无权限异常。
   * 创建标记
   */
  async addAnnotation(
    addAnnotationRequest?: AddAnnotationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AnnotationResponse> {
    const response = await this.addAnnotationRaw(
      { addAnnotationRequest: addAnnotationRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 添加轮播图列表
   */
  async addCarouselImagesListRaw(
    requestParameters: AddCarouselImagesListOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddCarouselImagesList200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/carousel/add`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: AddCarouselImagesListRequestToJSON(requestParameters['addCarouselImagesListRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AddCarouselImagesList200ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 添加轮播图列表
   */
  async addCarouselImagesList(
    addCarouselImagesListRequest?: AddCarouselImagesListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddCarouselImagesList200Response> {
    const response = await this.addCarouselImagesListRaw(
      { addCarouselImagesListRequest: addCarouselImagesListRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 当数据库中已有历史映射时，返回用户名已存在异常 补充说明：该接口有个潜在bug还没修，即当添加的协助者id就是场景创建者时，应该做对应的处理，否则同场景列表接口可能出现错误交互（比如返回重复场景）
   * 添加场景协作者
   * @deprecated
   */
  async addCollaboratorRaw(
    requestParameters: AddCollaboratorRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddCollaborator201Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/collaborator/add`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: CollabotatorRequestToJSON(requestParameters['collabotatorRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AddCollaborator201ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 当数据库中已有历史映射时，返回用户名已存在异常 补充说明：该接口有个潜在bug还没修，即当添加的协助者id就是场景创建者时，应该做对应的处理，否则同场景列表接口可能出现错误交互（比如返回重复场景）
   * 添加场景协作者
   * @deprecated
   */
  async addCollaborator(
    collabotatorRequest?: CollabotatorRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddCollaborator201Response> {
    const response = await this.addCollaboratorRaw(
      { collabotatorRequest: collabotatorRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 对tag的总表进行添加，不涉及场景操作
   * 添加标签tag列表
   */
  async addTagListRaw(
    requestParameters: AddTagListOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddTagList200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/tag/addList`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: AddTagListRequestToJSON(requestParameters['addTagListRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AddTagList200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 对tag的总表进行添加，不涉及场景操作
   * 添加标签tag列表
   */
  async addTagList(
    addTagListRequest?: AddTagListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddTagList200Response> {
    const response = await this.addTagListRaw(
      { addTagListRequest: addTagListRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 创建场景
   */
  async createSceneRaw(
    requestParameters: CreateSceneOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SceneResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/create`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: CreateSceneRequestToJSON(requestParameters['createSceneRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => SceneResponseFromJSON(jsonValue))
  }

  /**
   *
   * 创建场景
   */
  async createScene(
    createSceneRequest?: CreateSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SceneResponse> {
    const response = await this.createSceneRaw(
      { createSceneRequest: createSceneRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 删除场景
   */
  async deleteSceneRaw(
    requestParameters: DeleteSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteScene().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['id'] != null) {
      queryParameters['id'] = requestParameters['id']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   *
   * 删除场景
   */
  async deleteScene(
    id: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.deleteSceneRaw({ id: id }, initOverrides)
    return await response.value()
  }

  /**
   * 传回一个tag 的id列表，后台进行假删除 对tag的总表进行删除，不涉及场景操作
   * 删除标签tag列表
   */
  async deleteTagListRaw(
    requestParameters: DeleteTagListOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/tag/deleteList`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: DeleteTagListRequestToJSON(requestParameters['deleteTagListRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * 传回一个tag 的id列表，后台进行假删除 对tag的总表进行删除，不涉及场景操作
   * 删除标签tag列表
   */
  async deleteTagList(
    deleteTagListRequest?: DeleteTagListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.deleteTagListRaw(
      { deleteTagListRequest: deleteTagListRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 修改标记
   */
  async editAnnotationRaw(
    requestParameters: EditAnnotationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AnnotationResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/annotation/edit`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: EditAnnotationRequest1ToJSON(requestParameters['editAnnotationRequest1']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AnnotationResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 修改标记
   */
  async editAnnotation(
    editAnnotationRequest1?: EditAnnotationRequest1,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AnnotationResponse> {
    const response = await this.editAnnotationRaw(
      { editAnnotationRequest1: editAnnotationRequest1 },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 修改轮播图列表
   */
  async editCarouselImageListRaw(
    requestParameters: EditCarouselImageListOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EditCarouselImageList200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/carousel/edit`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: EditCarouselImageListRequestToJSON(requestParameters['editCarouselImageListRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EditCarouselImageList200ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 修改轮播图列表
   */
  async editCarouselImageList(
    editCarouselImageListRequest?: EditCarouselImageListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EditCarouselImageList200Response> {
    const response = await this.editCarouselImageListRaw(
      { editCarouselImageListRequest: editCarouselImageListRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * “tag”和“协作者”需要每次修改传回所有数据更新，birthPosition和birthRotation同理 (即想删除/修改“tag”和“协作者”只需要把修改后的结果传回来，进行更新即可
   * 修改场景
   */
  async editSceneRaw(
    requestParameters: EditSceneOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SceneResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/edit`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: EditSceneRequestToJSON(requestParameters['editSceneRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => SceneResponseFromJSON(jsonValue))
  }

  /**
   * “tag”和“协作者”需要每次修改传回所有数据更新，birthPosition和birthRotation同理 (即想删除/修改“tag”和“协作者”只需要把修改后的结果传回来，进行更新即可
   * 修改场景
   */
  async editScene(
    editSceneRequest?: EditSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SceneResponse> {
    const response = await this.editSceneRaw({ editSceneRequest: editSceneRequest }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 获取单个标记详情
   */
  async getAnnotationDetailsRaw(
    requestParameters: GetAnnotationDetailsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AnnotationResponse>> {
    if (requestParameters['annotationId'] == null) {
      throw new runtime.RequiredError(
        'annotationId',
        'Required parameter "annotationId" was null or undefined when calling getAnnotationDetails().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['annotationId'] != null) {
      queryParameters['annotationId'] = requestParameters['annotationId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/annotation/getInfo`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AnnotationResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 获取单个标记详情
   */
  async getAnnotationDetails(
    annotationId: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AnnotationResponse> {
    const response = await this.getAnnotationDetailsRaw(
      { annotationId: annotationId },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 获取场景信息
   */
  async getSceneRaw(
    requestParameters: GetSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SceneResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getScene().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['id'] != null) {
      queryParameters['id'] = requestParameters['id']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => SceneResponseFromJSON(jsonValue))
  }

  /**
   *
   * 获取场景信息
   */
  async getScene(
    id: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SceneResponse> {
    const response = await this.getSceneRaw({ id: id }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 获取封面
   * @deprecated
   */
  async getSceneCoverRaw(
    requestParameters: GetSceneCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CoverResponse>> {
    if (requestParameters['sceneId'] == null) {
      throw new runtime.RequiredError(
        'sceneId',
        'Required parameter "sceneId" was null or undefined when calling getSceneCover().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['sceneId'] != null) {
      queryParameters['sceneId'] = requestParameters['sceneId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/cover`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => CoverResponseFromJSON(jsonValue))
  }

  /**
   *
   * 获取封面
   * @deprecated
   */
  async getSceneCover(
    sceneId: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CoverResponse> {
    const response = await this.getSceneCoverRaw({ sceneId: sceneId }, initOverrides)
    return await response.value()
  }

  /**
   * 输入tag标签名，返回包含这个标签名的list，对tag的总表进行查询，不涉及场景操作
   * 查询标签tag列表
   */
  async getTagListByNameRaw(
    requestParameters: GetTagListByNameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetTagListByName200Response>> {
    if (requestParameters['tagName'] == null) {
      throw new runtime.RequiredError(
        'tagName',
        'Required parameter "tagName" was null or undefined when calling getTagListByName().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['tagName'] != null) {
      queryParameters['tagName'] = requestParameters['tagName']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/tag/List`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetTagListByName200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 输入tag标签名，返回包含这个标签名的list，对tag的总表进行查询，不涉及场景操作
   * 查询标签tag列表
   */
  async getTagListByName(
    tagName: string,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetTagListByName200Response> {
    const response = await this.getTagListByNameRaw({ tagName: tagName }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 获取点赞信息
   */
  async likedSceneRaw(
    requestParameters: LikedSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LikedScene200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/like`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: LikeSceneRequestToJSON(requestParameters['likeSceneRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LikedScene200ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 获取点赞信息
   */
  async likedScene(
    likeSceneRequest?: LikeSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LikedScene200Response> {
    const response = await this.likedSceneRaw({ likeSceneRequest: likeSceneRequest }, initOverrides)
    return await response.value()
  }

  /**
   * 返回的数据包含了annotationData。在后续修改标记的时候，比如传送点，前端页面会弹出该点的绑定信息，用于警告用户修改会覆盖原始数据。
   * 获取标记列表
   */
  async listAnnotationRaw(
    requestParameters: ListAnnotationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListAnnotationResponse>> {
    if (requestParameters['sceneId'] == null) {
      throw new runtime.RequiredError(
        'sceneId',
        'Required parameter "sceneId" was null or undefined when calling listAnnotation().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['sceneId'] != null) {
      queryParameters['sceneId'] = requestParameters['sceneId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/annotation/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListAnnotationResponseFromJSON(jsonValue),
    )
  }

  /**
   * 返回的数据包含了annotationData。在后续修改标记的时候，比如传送点，前端页面会弹出该点的绑定信息，用于警告用户修改会覆盖原始数据。
   * 获取标记列表
   */
  async listAnnotation(
    sceneId: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListAnnotationResponse> {
    const response = await this.listAnnotationRaw({ sceneId: sceneId }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 获取轮播图列表
   */
  async listCarouselImageRaw(
    requestParameters: ListCarouselImageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListCarouselImageResponse>> {
    const queryParameters: any = {}

    if (requestParameters['first'] != null) {
      queryParameters['first'] = requestParameters['first']
    }

    if (requestParameters['after'] != null) {
      queryParameters['after'] = requestParameters['after']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/carousel/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListCarouselImageResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 获取轮播图列表
   */
  async listCarouselImage(
    first?: number,
    after?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListCarouselImageResponse> {
    const response = await this.listCarouselImageRaw({ first: first, after: after }, initOverrides)
    return await response.value()
  }

  /**
   * 应该将该接口合并到获取场景信息接口中 获取场景信息接口应该提供协助者ID列表
   * 获取协助者列表
   * @deprecated
   */
  async listCollaboratorsRaw(
    requestParameters: ListCollaboratorsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListCollaborators200Response>> {
    if (requestParameters['sceneId'] == null) {
      throw new runtime.RequiredError(
        'sceneId',
        'Required parameter "sceneId" was null or undefined when calling listCollaborators().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['sceneId'] != null) {
      queryParameters['sceneId'] = requestParameters['sceneId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/collaborator/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListCollaborators200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 应该将该接口合并到获取场景信息接口中 获取场景信息接口应该提供协助者ID列表
   * 获取协助者列表
   * @deprecated
   */
  async listCollaborators(
    sceneId: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListCollaborators200Response> {
    const response = await this.listCollaboratorsRaw({ sceneId: sceneId }, initOverrides)
    return await response.value()
  }

  /**
   * 当不传入user_id时，获取所有公开场景 当传入user_id时，如果user_id==当前用户id，获取公开的和私有的场景，一并返回协作者场景 否则不返回协作者场景，并且只获取user_id的公开场景 获取回收站场景列表需要传入userid，参数isRecycleBin设为1
   * 获取场景列表
   */
  async listSceneRaw(
    requestParameters: ListSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListScenesResponse>> {
    const queryParameters: any = {}

    if (requestParameters['first'] != null) {
      queryParameters['first'] = requestParameters['first']
    }

    if (requestParameters['after'] != null) {
      queryParameters['after'] = requestParameters['after']
    }

    if (requestParameters['userId'] != null) {
      queryParameters['user_id'] = requestParameters['userId']
    }

    if (requestParameters['keyword'] != null) {
      queryParameters['keyword'] = requestParameters['keyword']
    }

    if (requestParameters['isRecycleBin'] != null) {
      queryParameters['isRecycleBin'] = requestParameters['isRecycleBin']
    }

    if (requestParameters['publicMode'] != null) {
      queryParameters['publicMode'] = requestParameters['publicMode']
    }

    if (requestParameters['tag'] != null) {
      queryParameters['tag'] = requestParameters['tag']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListScenesResponseFromJSON(jsonValue),
    )
  }

  /**
   * 当不传入user_id时，获取所有公开场景 当传入user_id时，如果user_id==当前用户id，获取公开的和私有的场景，一并返回协作者场景 否则不返回协作者场景，并且只获取user_id的公开场景 获取回收站场景列表需要传入userid，参数isRecycleBin设为1
   * 获取场景列表
   */
  async listScene(
    first?: number,
    after?: number,
    userId?: number,
    keyword?: string,
    isRecycleBin?: number,
    publicMode?: boolean,
    tag?: string,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListScenesResponse> {
    const response = await this.listSceneRaw(
      {
        first: first,
        after: after,
        userId: userId,
        keyword: keyword,
        isRecycleBin: isRecycleBin,
        publicMode: publicMode,
        tag: tag,
      },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 返回的标记点列表为排序后的列表
   * 修改排序
   */
  async orderAnnotationRaw(
    requestParameters: OrderAnnotationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListAnnotationResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/annotation/order`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: OrderAnnotationRequestToJSON(requestParameters['orderAnnotationRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListAnnotationResponseFromJSON(jsonValue),
    )
  }

  /**
   * 返回的标记点列表为排序后的列表
   * 修改排序
   */
  async orderAnnotation(
    orderAnnotationRequest?: OrderAnnotationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListAnnotationResponse> {
    const response = await this.orderAnnotationRaw(
      { orderAnnotationRequest: orderAnnotationRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 用户发送请求后，annotaitonId映射到sceneId，检查用户是否是对应sceneId的场景管理员，如果不是，返回无权限异常。
   * 删除标记
   */
  async removeAnnotationRaw(
    requestParameters: RemoveAnnotationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    const queryParameters: any = {}

    if (requestParameters['annotationId'] != null) {
      queryParameters['annotationId'] = requestParameters['annotationId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/annotation/remove`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * 用户发送请求后，annotaitonId映射到sceneId，检查用户是否是对应sceneId的场景管理员，如果不是，返回无权限异常。
   * 删除标记
   */
  async removeAnnotation(
    annotationId?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.removeAnnotationRaw({ annotationId: annotationId }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 移除场景协作者
   * @deprecated
   */
  async removeCollaboratorRaw(
    requestParameters: RemoveCollaboratorRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddCollaborator201Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/collaborator/remove`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CollabotatorRequestToJSON(requestParameters['collabotatorRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AddCollaborator201ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 移除场景协作者
   * @deprecated
   */
  async removeCollaborator(
    collabotatorRequest?: CollabotatorRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddCollaborator201Response> {
    const response = await this.removeCollaboratorRaw(
      { collabotatorRequest: collabotatorRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 撤销删除场景
   */
  async undoDeleteSceneRaw(
    requestParameters: UndoDeleteSceneRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling undoDeleteScene().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['id'] != null) {
      queryParameters['id'] = requestParameters['id']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/delete/undo`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   *
   * 撤销删除场景
   */
  async undoDeleteScene(
    id: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.undoDeleteSceneRaw({ id: id }, initOverrides)
    return await response.value()
  }

  /**
   * 上传封面图片到腾讯云对象存储 上传到/scene/{{sceneId}}/cover.jpg 当从token中解析出来的用户ID不是场景创建或协作者者时，返回无权限异常 审核失败时，也返回400无法解析图片异常 补充说明：后端有个测试可以跑，见sceneApiControllerTest中的testUploadCover方法，把group.jpg替换成你想要上传的图片文件，访问测试返回响应中的url就能下载图片文件（可能有点延迟）
   * 上传封面
   * @deprecated
   */
  async uploadCoverRaw(
    requestParameters: UploadCoverOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CoverResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/cover/upload`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UploadCoverRequestToJSON(requestParameters['uploadCoverRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => CoverResponseFromJSON(jsonValue))
  }

  /**
   * 上传封面图片到腾讯云对象存储 上传到/scene/{{sceneId}}/cover.jpg 当从token中解析出来的用户ID不是场景创建或协作者者时，返回无权限异常 审核失败时，也返回400无法解析图片异常 补充说明：后端有个测试可以跑，见sceneApiControllerTest中的testUploadCover方法，把group.jpg替换成你想要上传的图片文件，访问测试返回响应中的url就能下载图片文件（可能有点延迟）
   * 上传封面
   * @deprecated
   */
  async uploadCover(
    uploadCoverRequest?: UploadCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CoverResponse> {
    const response = await this.uploadCoverRaw(
      { uploadCoverRequest: uploadCoverRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * #### 要求限制文件大小20MB以内
   * 介绍点上传图片
   */
  async uploadIntroductionImageRaw(
    requestParameters: UploadIntroductionImageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UploadIntroductionImage200Response>> {
    if (requestParameters['jpgFile'] == null) {
      throw new runtime.RequiredError(
        'jpgFile',
        'Required parameter "jpgFile" was null or undefined when calling uploadIntroductionImage().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const consumes: runtime.Consume[] = [{ contentType: 'multipart/form-data' }]
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes)

    let formParams: { append(param: string, value: any): any }
    let useForm = false
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm
    if (useForm) {
      formParams = new FormData()
    } else {
      formParams = new URLSearchParams()
    }

    if (requestParameters['jpgFile'] != null) {
      formParams.append('jpgFile', requestParameters['jpgFile'] as any)
    }

    const response = await this.request(
      {
        path: `/scene/upload/image`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UploadIntroductionImage200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * #### 要求限制文件大小20MB以内
   * 介绍点上传图片
   */
  async uploadIntroductionImage(
    jpgFile: Blob,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UploadIntroductionImage200Response> {
    const response = await this.uploadIntroductionImageRaw({ jpgFile: jpgFile }, initOverrides)
    return await response.value()
  }

  /**
   * #### 要求限制视频大小20MB以内，目前限制格式为MP4，建议在前端写明
   * 介绍点上传视频
   */
  async uploadVideoRaw(
    requestParameters: UploadVideoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UploadVideo200Response>> {
    if (requestParameters['videoFile'] == null) {
      throw new runtime.RequiredError(
        'videoFile',
        'Required parameter "videoFile" was null or undefined when calling uploadVideo().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const consumes: runtime.Consume[] = [{ contentType: 'multipart/form-data' }]
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes)

    let formParams: { append(param: string, value: any): any }
    let useForm = false
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm
    if (useForm) {
      formParams = new FormData()
    } else {
      formParams = new URLSearchParams()
    }

    if (requestParameters['videoFile'] != null) {
      formParams.append('videoFile', requestParameters['videoFile'] as any)
    }

    const response = await this.request(
      {
        path: `/scene/upload/video`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UploadVideo200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * #### 要求限制视频大小20MB以内，目前限制格式为MP4，建议在前端写明
   * 介绍点上传视频
   */
  async uploadVideo(
    videoFile: Blob,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UploadVideo200Response> {
    const response = await this.uploadVideoRaw({ videoFile: videoFile }, initOverrides)
    return await response.value()
  }
}
