/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  AddTagList200Response,
  AddTagListRequest,
  CreateScene400Response,
  DeleteTagListRequest,
  GetTagListByName200Response,
  UploadCover400Response,
} from '../models/index'
import {
  AddTagList200ResponseFromJSON,
  AddTagList200ResponseToJSON,
  AddTagListRequestFromJSON,
  AddTagListRequestToJSON,
  CreateScene400ResponseFromJSON,
  CreateScene400ResponseToJSON,
  DeleteTagListRequestFromJSON,
  DeleteTagListRequestToJSON,
  GetTagListByName200ResponseFromJSON,
  GetTagListByName200ResponseToJSON,
  UploadCover400ResponseFromJSON,
  UploadCover400ResponseToJSON,
} from '../models/index'

export interface AddTagListOperationRequest {
  addTagListRequest?: AddTagListRequest
}

export interface DeleteTagListOperationRequest {
  deleteTagListRequest?: DeleteTagListRequest
}

export interface GetTagListByNameRequest {
  tagName: string
}

/**
 *
 */
export class TagApi extends runtime.BaseAPI {
  /**
   * 对tag的总表进行添加，不涉及场景操作
   * 添加标签tag列表
   */
  async addTagListRaw(
    requestParameters: AddTagListOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddTagList200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/tag/addList`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: AddTagListRequestToJSON(requestParameters['addTagListRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AddTagList200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 对tag的总表进行添加，不涉及场景操作
   * 添加标签tag列表
   */
  async addTagList(
    addTagListRequest?: AddTagListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddTagList200Response> {
    const response = await this.addTagListRaw(
      { addTagListRequest: addTagListRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 传回一个tag 的id列表，后台进行假删除 对tag的总表进行删除，不涉及场景操作
   * 删除标签tag列表
   */
  async deleteTagListRaw(
    requestParameters: DeleteTagListOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/tag/deleteList`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: DeleteTagListRequestToJSON(requestParameters['deleteTagListRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * 传回一个tag 的id列表，后台进行假删除 对tag的总表进行删除，不涉及场景操作
   * 删除标签tag列表
   */
  async deleteTagList(
    deleteTagListRequest?: DeleteTagListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.deleteTagListRaw(
      { deleteTagListRequest: deleteTagListRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 输入tag标签名，返回包含这个标签名的list，对tag的总表进行查询，不涉及场景操作
   * 查询标签tag列表
   */
  async getTagListByNameRaw(
    requestParameters: GetTagListByNameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetTagListByName200Response>> {
    if (requestParameters['tagName'] == null) {
      throw new runtime.RequiredError(
        'tagName',
        'Required parameter "tagName" was null or undefined when calling getTagListByName().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['tagName'] != null) {
      queryParameters['tagName'] = requestParameters['tagName']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/scene/tag/List`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetTagListByName200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 输入tag标签名，返回包含这个标签名的list，对tag的总表进行查询，不涉及场景操作
   * 查询标签tag列表
   */
  async getTagListByName(
    tagName: string,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetTagListByName200Response> {
    const response = await this.getTagListByNameRaw({ tagName: tagName }, initOverrides)
    return await response.value()
  }
}
