/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  CreateScene400Response,
  DeleteUser200Response,
  FavoriteListResponse,
  FavoriteSceneCrudRequest,
  FavouritesCrudRequest,
  FavouritesListResponse,
  GetUserInfoResponse,
  ListSceneHistroyResponse,
  ListUserInfoResponse,
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  UpdatePassword200Response,
  UpdatePasswordRequest,
  UpdateUserInfo200Response,
  UpdateUserInfoRequest,
  UploadCover400Response,
} from '../models/index'
import {
  CreateScene400ResponseFromJSON,
  CreateScene400ResponseToJSON,
  DeleteUser200ResponseFromJSON,
  DeleteUser200ResponseToJSON,
  FavoriteListResponseFromJSON,
  FavoriteListResponseToJSON,
  FavoriteSceneCrudRequestFromJSON,
  FavoriteSceneCrudRequestToJSON,
  FavouritesCrudRequestFromJSON,
  FavouritesCrudRequestToJSON,
  FavouritesListResponseFromJSON,
  FavouritesListResponseToJSON,
  GetUserInfoResponseFromJSON,
  GetUserInfoResponseToJSON,
  ListSceneHistroyResponseFromJSON,
  ListSceneHistroyResponseToJSON,
  ListUserInfoResponseFromJSON,
  ListUserInfoResponseToJSON,
  LoginRequestFromJSON,
  LoginRequestToJSON,
  LoginResponseFromJSON,
  LoginResponseToJSON,
  RegisterRequestFromJSON,
  RegisterRequestToJSON,
  UpdatePassword200ResponseFromJSON,
  UpdatePassword200ResponseToJSON,
  UpdatePasswordRequestFromJSON,
  UpdatePasswordRequestToJSON,
  UpdateUserInfo200ResponseFromJSON,
  UpdateUserInfo200ResponseToJSON,
  UpdateUserInfoRequestFromJSON,
  UpdateUserInfoRequestToJSON,
  UploadCover400ResponseFromJSON,
  UploadCover400ResponseToJSON,
} from '../models/index'

export interface DeleteUserRequest {
  body?: object
}

export interface FavoriteCRUDRequest {
  favoriteSceneCrudRequest?: FavoriteSceneCrudRequest
}

export interface FavouritesCRUDRequest {
  favouritesCrudRequest?: FavouritesCrudRequest
}

export interface GetUserInfoRequest {
  id?: number
}

export interface GetUserListByNameRequest {
  name?: string
}

export interface GetUserSceneHistoryRequest {
  first?: number
  after?: number
}

export interface LoginOperationRequest {
  loginRequest?: LoginRequest
}

export interface RegisterOperationRequest {
  registerRequest?: RegisterRequest
}

export interface UpdatePasswordOperationRequest {
  updatePasswordRequest?: UpdatePasswordRequest
}

export interface UpdateUserInfoOperationRequest {
  updateUserInfoRequest?: UpdateUserInfoRequest
}

/**
 *
 */
export class UserApi extends runtime.BaseAPI {
  /**
   *
   * 删除用户
   */
  async deleteUserRaw(
    requestParameters: DeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DeleteUser200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/delete`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['body'] as any,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeleteUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 删除用户
   */
  async deleteUser(
    body?: object,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DeleteUser200Response> {
    const response = await this.deleteUserRaw({ body: body }, initOverrides)
    return await response.value()
  }

  /**
   * create:添加新的收藏场景 read:列出所有收藏场景 update:用新的sceneId数组覆写旧的,参考修改协助者列表 delete:删除收藏场景
   * 收藏场景增删查改
   */
  async favoriteCRUDRaw(
    requestParameters: FavoriteCRUDRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FavoriteListResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/favourites/favorite/crud`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: FavoriteSceneCrudRequestToJSON(requestParameters['favoriteSceneCrudRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FavoriteListResponseFromJSON(jsonValue),
    )
  }

  /**
   * create:添加新的收藏场景 read:列出所有收藏场景 update:用新的sceneId数组覆写旧的,参考修改协助者列表 delete:删除收藏场景
   * 收藏场景增删查改
   */
  async favoriteCRUD(
    favoriteSceneCrudRequest?: FavoriteSceneCrudRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FavoriteListResponse> {
    const response = await this.favoriteCRUDRaw(
      { favoriteSceneCrudRequest: favoriteSceneCrudRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 收藏夹crud create:创建新的收藏夹，需要收藏夹名称 read:列出所有收藏夹，总是包含default，不需要参数 update:修改收藏夹，需要目标收藏夹名称以及修改后的新的收藏夹名称，目标收藏夹名称不应该是default delete:删除目标收藏夹，default不可删除 将校验operation同body是否匹配，包括operation==read时，要求body为空，body:{}
   * 收藏夹增删查改
   */
  async favouritesCRUDRaw(
    requestParameters: FavouritesCRUDRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FavouritesListResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/favourites/crud`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: FavouritesCrudRequestToJSON(requestParameters['favouritesCrudRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FavouritesListResponseFromJSON(jsonValue),
    )
  }

  /**
   * 收藏夹crud create:创建新的收藏夹，需要收藏夹名称 read:列出所有收藏夹，总是包含default，不需要参数 update:修改收藏夹，需要目标收藏夹名称以及修改后的新的收藏夹名称，目标收藏夹名称不应该是default delete:删除目标收藏夹，default不可删除 将校验operation同body是否匹配，包括operation==read时，要求body为空，body:{}
   * 收藏夹增删查改
   */
  async favouritesCRUD(
    favouritesCrudRequest?: FavouritesCrudRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FavouritesListResponse> {
    const response = await this.favouritesCRUDRaw(
      { favouritesCrudRequest: favouritesCrudRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 根据 ID 查询用户信息
   */
  async getUserInfoRaw(
    requestParameters: GetUserInfoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUserInfoResponse>> {
    const queryParameters: any = {}

    if (requestParameters['id'] != null) {
      queryParameters['id'] = requestParameters['id']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/info`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUserInfoResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 根据 ID 查询用户信息
   */
  async getUserInfo(
    id?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUserInfoResponse> {
    const response = await this.getUserInfoRaw({ id: id }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 名字查询用户信息
   */
  async getUserListByNameRaw(
    requestParameters: GetUserListByNameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListUserInfoResponse>> {
    const queryParameters: any = {}

    if (requestParameters['name'] != null) {
      queryParameters['name'] = requestParameters['name']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/infoByName`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListUserInfoResponseFromJSON(jsonValue),
    )
  }

  /**
   *
   * 名字查询用户信息
   */
  async getUserListByName(
    name?: string,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListUserInfoResponse> {
    const response = await this.getUserListByNameRaw({ name: name }, initOverrides)
    return await response.value()
  }

  /**
   * 获取当前用户记录 前50条从Redis获取，但是返回结果可能会多于50条，因为每晚0点才把redis刷入mysql 负数表示从Redis中获取的数据 如果返回结果以正数开头的话，表明采取了服务降级
   * 获取用户浏览历史
   */
  async getUserSceneHistoryRaw(
    requestParameters: GetUserSceneHistoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListSceneHistroyResponse>> {
    const queryParameters: any = {}

    if (requestParameters['first'] != null) {
      queryParameters['first'] = requestParameters['first']
    }

    if (requestParameters['after'] != null) {
      queryParameters['after'] = requestParameters['after']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/scene/history`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListSceneHistroyResponseFromJSON(jsonValue),
    )
  }

  /**
   * 获取当前用户记录 前50条从Redis获取，但是返回结果可能会多于50条，因为每晚0点才把redis刷入mysql 负数表示从Redis中获取的数据 如果返回结果以正数开头的话，表明采取了服务降级
   * 获取用户浏览历史
   */
  async getUserSceneHistory(
    first?: number,
    after?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListSceneHistroyResponse> {
    const response = await this.getUserSceneHistoryRaw(
      { first: first, after: after },
      initOverrides,
    )
    return await response.value()
  }

  /**
   *
   * 用户登录
   */
  async loginRaw(
    requestParameters: LoginOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/user/login`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: LoginRequestToJSON(requestParameters['loginRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue))
  }

  /**
   *
   * 用户登录
   */
  async login(
    loginRequest?: LoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LoginResponse> {
    const response = await this.loginRaw({ loginRequest: loginRequest }, initOverrides)
    return await response.value()
  }

  /**
   *
   * 用户注册
   */
  async registerRaw(
    requestParameters: RegisterOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/user/register`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RegisterRequestToJSON(requestParameters['registerRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   *
   * 用户注册
   */
  async register(
    registerRequest?: RegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.registerRaw({ registerRequest: registerRequest }, initOverrides)
    return await response.value()
  }

  /**
   * ### 修改密码会产生新的Token
   * 修改密码
   */
  async updatePasswordRaw(
    requestParameters: UpdatePasswordOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdatePassword200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/User/updatePassword`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: UpdatePasswordRequestToJSON(requestParameters['updatePasswordRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdatePassword200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * ### 修改密码会产生新的Token
   * 修改密码
   */
  async updatePassword(
    updatePasswordRequest?: UpdatePasswordRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdatePassword200Response> {
    const response = await this.updatePasswordRaw(
      { updatePasswordRequest: updatePasswordRequest },
      initOverrides,
    )
    return await response.value()
  }

  /**
   * 目前支持修改头像，用户名，昵称，签名，性别，生日，地址，置顶场景 置顶场景：限制3个，并且置顶场景只涉及覆盖操作，若为空表示不做修改 日期要求参数字符串格式 “YYYY-MM-DD” 后续可以添加
   * 更新用户信息
   */
  async updateUserInfoRaw(
    requestParameters: UpdateUserInfoOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdateUserInfo200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearer', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/user/updateInfo`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateUserInfoRequestToJSON(requestParameters['updateUserInfoRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdateUserInfo200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 目前支持修改头像，用户名，昵称，签名，性别，生日，地址，置顶场景 置顶场景：限制3个，并且置顶场景只涉及覆盖操作，若为空表示不做修改 日期要求参数字符串格式 “YYYY-MM-DD” 后续可以添加
   * 更新用户信息
   */
  async updateUserInfo(
    updateUserInfoRequest?: UpdateUserInfoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdateUserInfo200Response> {
    const response = await this.updateUserInfoRaw(
      { updateUserInfoRequest: updateUserInfoRequest },
      initOverrides,
    )
    return await response.value()
  }
}
