/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AnnotationData } from './AnnotationData'
import {
  AnnotationDataFromJSON,
  AnnotationDataFromJSONTyped,
  AnnotationDataToJSON,
} from './AnnotationData'

/**
 *
 * @export
 * @interface AddAnnotationRequest
 */
export interface AddAnnotationRequest {
  /**
   *
   * @type {number}
   * @memberof AddAnnotationRequest
   */
  sceneId: number | null
  /**
   *
   * @type {number}
   * @memberof AddAnnotationRequest
   */
  positionX: number
  /**
   *
   * @type {number}
   * @memberof AddAnnotationRequest
   */
  positionY: number
  /**
   *
   * @type {number}
   * @memberof AddAnnotationRequest
   */
  positionZ: number
  /**
   * 标记球体半径
   * @type {number}
   * @memberof AddAnnotationRequest
   */
  radius: number
  /**
   * 用字符串表示颜色，如"#FF0000"表示红色，需要验证字符串合法性
   * @type {string}
   * @memberof AddAnnotationRequest
   */
  color: string
  /**
   * 名称
   * @type {string}
   * @memberof AddAnnotationRequest
   */
  name: string
  /**
   *
   * @type {AnnotationData}
   * @memberof AddAnnotationRequest
   */
  annotationData: AnnotationData
}

/**
 * Check if a given object implements the AddAnnotationRequest interface.
 */
export function instanceOfAddAnnotationRequest(value: object): boolean {
  if (!('sceneId' in value)) return false
  if (!('positionX' in value)) return false
  if (!('positionY' in value)) return false
  if (!('positionZ' in value)) return false
  if (!('radius' in value)) return false
  if (!('color' in value)) return false
  if (!('name' in value)) return false
  if (!('annotationData' in value)) return false
  return true
}

export function AddAnnotationRequestFromJSON(json: any): AddAnnotationRequest {
  return AddAnnotationRequestFromJSONTyped(json, false)
}

export function AddAnnotationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddAnnotationRequest {
  if (json == null) {
    return json
  }
  return {
    sceneId: json['sceneId'],
    positionX: json['position_x'],
    positionY: json['position_y'],
    positionZ: json['position_z'],
    radius: json['radius'],
    color: json['color'],
    name: json['name'],
    annotationData: json['annotationData'],
  }
}

export function AddAnnotationRequestToJSON(value?: AddAnnotationRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    sceneId: value['sceneId'],
    position_x: value['positionX'],
    position_y: value['positionY'],
    position_z: value['positionZ'],
    radius: value['radius'],
    color: value['color'],
    name: value['name'],
    annotationData: value['annotationData'],
  }
}
