/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CarouselImageResponse } from './CarouselImageResponse'
import {
  CarouselImageResponseFromJSON,
  CarouselImageResponseFromJSONTyped,
  CarouselImageResponseToJSON,
} from './CarouselImageResponse'

/**
 *
 * @export
 * @interface AddCarouselImagesList200Response
 */
export interface AddCarouselImagesList200Response {
  /**
   *
   * @type {Array<CarouselImageResponse>}
   * @memberof AddCarouselImagesList200Response
   */
  carouselImageList: Array<CarouselImageResponse>
}

/**
 * Check if a given object implements the AddCarouselImagesList200Response interface.
 */
export function instanceOfAddCarouselImagesList200Response(value: object): boolean {
  if (!('carouselImageList' in value)) return false
  return true
}

export function AddCarouselImagesList200ResponseFromJSON(
  json: any,
): AddCarouselImagesList200Response {
  return AddCarouselImagesList200ResponseFromJSONTyped(json, false)
}

export function AddCarouselImagesList200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddCarouselImagesList200Response {
  if (json == null) {
    return json
  }
  return {
    carouselImageList: (json['CarouselImageList'] as Array<any>).map(CarouselImageResponseFromJSON),
  }
}

export function AddCarouselImagesList200ResponseToJSON(
  value?: AddCarouselImagesList200Response | null,
): any {
  if (value == null) {
    return value
  }
  return {
    CarouselImageList: (value['carouselImageList'] as Array<any>).map(CarouselImageResponseToJSON),
  }
}
