/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AddCarouselImageItem
 */
export interface AddCarouselImageItem {
  /**
   * 添加人
   * @type {number}
   * @memberof AddCarouselImageItem
   */
  creatorId: number
  /**
   * 场景 ID
   * @type {number}
   * @memberof AddCarouselImageItem
   */
  sceneId: number
  /**
   * 轮播图 URL，可以和场景封面图不同
   * @type {string}
   * @memberof AddCarouselImageItem
   */
  url: string
  /**
   * 图片的描述说明
   * @type {string}
   * @memberof AddCarouselImageItem
   */
  caption?: string
  /**
   * 图片在轮播图里的显示顺序，为空，默认为最后一位
   * @type {number}
   * @memberof AddCarouselImageItem
   */
  orderIndex?: number
}

/**
 * Check if a given object implements the AddCarouselImageItem interface.
 */
export function instanceOfAddCarouselImageItem(value: object): boolean {
  if (!('creatorId' in value)) return false
  if (!('sceneId' in value)) return false
  if (!('url' in value)) return false
  return true
}

export function AddCarouselImageItemFromJSON(json: any): AddCarouselImageItem {
  return AddCarouselImageItemFromJSONTyped(json, false)
}

export function AddCarouselImageItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddCarouselImageItem {
  if (json == null) {
    return json
  }
  return {
    creatorId: json['creatorId'],
    sceneId: json['sceneId'],
    url: json['url'],
    caption: json['caption'] == null ? undefined : json['caption'],
    orderIndex: json['orderIndex'] == null ? undefined : json['orderIndex'],
  }
}

export function AddCarouselImageItemToJSON(value?: AddCarouselImageItem | null): any {
  if (value == null) {
    return value
  }
  return {
    creatorId: value['creatorId'],
    sceneId: value['sceneId'],
    url: value['url'],
    caption: value['caption'],
    orderIndex: value['orderIndex'],
  }
}
