/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AddCarouselImageItem } from './AddCarouselImageItem'
import {
  AddCarouselImageItemFromJSON,
  AddCarouselImageItemFromJSONTyped,
  AddCarouselImageItemToJSON,
} from './AddCarouselImageItem'

/**
 *
 * @export
 * @interface AddCarouselImageRequest
 */
export interface AddCarouselImageRequest {
  /**
   *
   * @type {Array<AddCarouselImageItem>}
   * @memberof AddCarouselImageRequest
   */
  carouselImageList: Array<AddCarouselImageItem>
}

/**
 * Check if a given object implements the AddCarouselImageRequest interface.
 */
export function instanceOfAddCarouselImageRequest(value: object): boolean {
  if (!('carouselImageList' in value)) return false
  return true
}

export function AddCarouselImageRequestFromJSON(json: any): AddCarouselImageRequest {
  return AddCarouselImageRequestFromJSONTyped(json, false)
}

export function AddCarouselImageRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddCarouselImageRequest {
  if (json == null) {
    return json
  }
  return {
    carouselImageList: (json['CarouselImageList'] as Array<any>).map(AddCarouselImageItemFromJSON),
  }
}

export function AddCarouselImageRequestToJSON(value?: AddCarouselImageRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    CarouselImageList: (value['carouselImageList'] as Array<any>).map(AddCarouselImageItemToJSON),
  }
}
