/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CarouselImageResponse } from './CarouselImageResponse'
import {
  CarouselImageResponseFromJSON,
  CarouselImageResponseFromJSONTyped,
  CarouselImageResponseToJSON,
} from './CarouselImageResponse'

/**
 *
 * @export
 * @interface AddCarouselImageResponse
 */
export interface AddCarouselImageResponse {
  /**
   *
   * @type {Array<CarouselImageResponse>}
   * @memberof AddCarouselImageResponse
   */
  carouselImageList: Array<CarouselImageResponse>
}

/**
 * Check if a given object implements the AddCarouselImageResponse interface.
 */
export function instanceOfAddCarouselImageResponse(value: object): boolean {
  if (!('carouselImageList' in value)) return false
  return true
}

export function AddCarouselImageResponseFromJSON(json: any): AddCarouselImageResponse {
  return AddCarouselImageResponseFromJSONTyped(json, false)
}

export function AddCarouselImageResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddCarouselImageResponse {
  if (json == null) {
    return json
  }
  return {
    carouselImageList: (json['CarouselImageList'] as Array<any>).map(CarouselImageResponseFromJSON),
  }
}

export function AddCarouselImageResponseToJSON(value?: AddCarouselImageResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    CarouselImageList: (value['carouselImageList'] as Array<any>).map(CarouselImageResponseToJSON),
  }
}
