/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AddCollaborator201Response
 */
export interface AddCollaborator201Response {
  /**
   *
   * @type {string}
   * @memberof AddCollaborator201Response
   */
  message: string
}

/**
 * Check if a given object implements the AddCollaborator201Response interface.
 */
export function instanceOfAddCollaborator201Response(value: object): boolean {
  if (!('message' in value)) return false
  return true
}

export function AddCollaborator201ResponseFromJSON(json: any): AddCollaborator201Response {
  return AddCollaborator201ResponseFromJSONTyped(json, false)
}

export function AddCollaborator201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddCollaborator201Response {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function AddCollaborator201ResponseToJSON(value?: AddCollaborator201Response | null): any {
  if (value == null) {
    return value
  }
  return {
    message: value['message'],
  }
}
