/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { TagsModel } from './TagsModel'
import { TagsModelFromJSON, TagsModelFromJSONTyped, TagsModelToJSON } from './TagsModel'

/**
 *
 * @export
 * @interface AddTagList200Response
 */
export interface AddTagList200Response {
  /**
   * ID 编号
   * @type {Array<TagsModel>}
   * @memberof AddTagList200Response
   */
  tagsList: Array<TagsModel>
}

/**
 * Check if a given object implements the AddTagList200Response interface.
 */
export function instanceOfAddTagList200Response(value: object): boolean {
  if (!('tagsList' in value)) return false
  return true
}

export function AddTagList200ResponseFromJSON(json: any): AddTagList200Response {
  return AddTagList200ResponseFromJSONTyped(json, false)
}

export function AddTagList200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddTagList200Response {
  if (json == null) {
    return json
  }
  return {
    tagsList: (json['tagsList'] as Array<any>).map(TagsModelFromJSON),
  }
}

export function AddTagList200ResponseToJSON(value?: AddTagList200Response | null): any {
  if (value == null) {
    return value
  }
  return {
    tagsList: (value['tagsList'] as Array<any>).map(TagsModelToJSON),
  }
}
