/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AddTagListRequest
 */
export interface AddTagListRequest {
  /**
   * 标签
   * @type {Array<string>}
   * @memberof AddTagListRequest
   */
  tags: Array<string>
}

/**
 * Check if a given object implements the AddTagListRequest interface.
 */
export function instanceOfAddTagListRequest(value: object): boolean {
  if (!('tags' in value)) return false
  return true
}

export function AddTagListRequestFromJSON(json: any): AddTagListRequest {
  return AddTagListRequestFromJSONTyped(json, false)
}

export function AddTagListRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddTagListRequest {
  if (json == null) {
    return json
  }
  return {
    tags: json['tags'],
  }
}

export function AddTagListRequestToJSON(value?: AddTagListRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    tags: value['tags'],
  }
}
