/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AnnotationTransmission
 */
export interface AnnotationTransmission {
  /**
   *
   * @type {string}
   * @memberof AnnotationTransmission
   */
  type: AnnotationTransmissionTypeV4Compat
  /**
   * 要传送到的场景 ID
   * @type {number}
   * @memberof AnnotationTransmission
   */
  toSceneId: number
  /**
   * 目标传送点 ID
   * @type {number}
   * @memberof AnnotationTransmission
   */
  toTransmissionAnnotationId?: number
}

/**
 * @export
 */
export const AnnotationTransmissionTypeV4Compat = {
  Transmission: 'transmission',
} as const
export type AnnotationTransmissionTypeV4Compat =
  (typeof AnnotationTransmissionTypeV4Compat)[keyof typeof AnnotationTransmissionTypeV4Compat]

/**
 * Check if a given object implements the AnnotationTransmission interface.
 */
export function instanceOfAnnotationTransmission(value: object): boolean {
  if (!('type' in value)) return false
  if (!('toSceneId' in value)) return false
  return true
}

export function AnnotationTransmissionFromJSON(json: any): AnnotationTransmission {
  return AnnotationTransmissionFromJSONTyped(json, false)
}

export function AnnotationTransmissionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnnotationTransmission {
  if (json == null || !json['type'] || json['type'] !== 'transmission') {
    return json
  }
  return {
    type: json['type'],
    toSceneId: json['toSceneId'],
    toTransmissionAnnotationId:
      json['toTransmissionAnnotationId'] == null ? undefined : json['toTransmissionAnnotationId'],
  }
}

export function AnnotationTransmissionToJSON(value?: AnnotationTransmission | null): any {
  if (value == null) {
    return value
  }
  return {
    type: value['type'],
    toSceneId: value['toSceneId'],
    toTransmissionAnnotationId: value['toTransmissionAnnotationId'],
  }
}
