/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const AnnotationType = {
  Introduction: 'introduction',
  Navigation: 'navigation',
  Transmission: 'transmission',
} as const
export type AnnotationType = (typeof AnnotationType)[keyof typeof AnnotationType]

export function instanceOfAnnotationType(value: any): boolean {
  return Object.values(AnnotationType).includes(value)
}

export function AnnotationTypeFromJSON(json: any): AnnotationType {
  return AnnotationTypeFromJSONTyped(json, false)
}

export function AnnotationTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnnotationType {
  return json as AnnotationType
}

export function AnnotationTypeToJSON(value?: AnnotationType | null): any {
  return value as any
}
