/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AnnotationIntroduction
 */
export interface AnnotationIntroduction {
  /**
   *
   * @type {string}
   * @memberof AnnotationIntroduction
   */
  type: AnnotationIntroductionTypeV4Compat
  /**
   *
   * @type {string}
   * @memberof AnnotationIntroduction
   */
  briefIntroduction?: string
  /**
   *
   * @type {string}
   * @memberof AnnotationIntroduction
   */
  introduction?: string
  /**
   * 图片url
   * @type {string}
   * @memberof AnnotationIntroduction
   */
  imageUrl?: string
  /**
   * 语音url
   * @type {string}
   * @memberof AnnotationIntroduction
   */
  audioUrl?: string
  /**
   * 视频url
   * @type {string}
   * @memberof AnnotationIntroduction
   */
  video?: string
  /**
   *
   * @type {number}
   * @memberof AnnotationIntroduction
   */
  focalPointViewX?: number
  /**
   *
   * @type {number}
   * @memberof AnnotationIntroduction
   */
  focalPointViewY?: number
  /**
   *
   * @type {number}
   * @memberof AnnotationIntroduction
   */
  focalPointViewZ?: number
}

/**
 * @export
 */
export const AnnotationIntroductionTypeV4Compat = {
  Introduction: 'introduction',
} as const
export type AnnotationIntroductionTypeV4Compat =
  (typeof AnnotationIntroductionTypeV4Compat)[keyof typeof AnnotationIntroductionTypeV4Compat]

/**
 * Check if a given object implements the AnnotationIntroduction interface.
 */
export function instanceOfAnnotationIntroduction(value: object): boolean {
  if (!('type' in value)) return false
  return true
}

export function AnnotationIntroductionFromJSON(json: any): AnnotationIntroduction {
  return AnnotationIntroductionFromJSONTyped(json, false)
}

export function AnnotationIntroductionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnnotationIntroduction {
  if (json == null || !json['type'] || json['type'] !== 'introduction') {
    return json
  }
  return {
    type: json['type'],
    briefIntroduction: json['briefIntroduction'] == null ? undefined : json['briefIntroduction'],
    introduction: json['introduction'] == null ? undefined : json['introduction'],
    imageUrl: json['imageUrl'] == null ? undefined : json['imageUrl'],
    audioUrl: json['audioUrl'] == null ? undefined : json['audioUrl'],
    video: json['video'] == null ? undefined : json['video'],
    focalPointViewX: json['focalPointViewX'] == null ? undefined : json['focalPointViewX'],
    focalPointViewY: json['focalPointViewY'] == null ? undefined : json['focalPointViewY'],
    focalPointViewZ: json['focalPointViewZ'] == null ? undefined : json['focalPointViewZ'],
  }
}

export function AnnotationIntroductionToJSON(value?: AnnotationIntroduction | null): any {
  if (value == null) {
    return value
  }
  return {
    type: value['type'],
    briefIntroduction: value['briefIntroduction'],
    introduction: value['introduction'],
    imageUrl: value['imageUrl'],
    audioUrl: value['audioUrl'],
    video: value['video'],
    focalPointViewX: value['focalPointViewX'],
    focalPointViewY: value['focalPointViewY'],
    focalPointViewZ: value['focalPointViewZ'],
  }
}
