/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Line } from './Line'
import { LineFromJSON, LineFromJSONTyped, LineToJSON } from './Line'

/**
 *
 * @export
 * @interface AnnotationNavigation
 */
export interface AnnotationNavigation {
  /**
   *
   * @type {string}
   * @memberof AnnotationNavigation
   */
  type: AnnotationNavigationTypeV4Compat
  /**
   *
   * @type {Array<Line>}
   * @memberof AnnotationNavigation
   */
  linePointList?: Array<Line>
}

/**
 * @export
 */
export const AnnotationNavigationTypeV4Compat = {
  Navigation: 'navigation',
} as const
export type AnnotationNavigationTypeV4Compat =
  (typeof AnnotationNavigationTypeV4Compat)[keyof typeof AnnotationNavigationTypeV4Compat]

/**
 * Check if a given object implements the AnnotationNavigation interface.
 */
export function instanceOfAnnotationNavigation(value: object): boolean {
  if (!('type' in value)) return false
  return true
}

export function AnnotationNavigationFromJSON(json: any): AnnotationNavigation {
  return AnnotationNavigationFromJSONTyped(json, false)
}

export function AnnotationNavigationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnnotationNavigation {
  if (json == null || !json['type'] || json['type'] !== 'navigation') {
    return json
  }
  return {
    type: json['type'],
    linePointList:
      json['linePointList'] == null
        ? undefined
        : (json['linePointList'] as Array<any>).map(LineFromJSON),
  }
}

export function AnnotationNavigationToJSON(value?: AnnotationNavigation | null): any {
  if (value == null) {
    return value
  }
  return {
    type: value['type'],
    linePointList:
      value['linePointList'] == null
        ? undefined
        : (value['linePointList'] as Array<any>).map(LineToJSON),
  }
}
