/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AnnotationIntroduction } from './AnnotationIntroduction'
import {
  instanceOfAnnotationIntroduction,
  AnnotationIntroductionFromJSON,
  AnnotationIntroductionFromJSONTyped,
  AnnotationIntroductionToJSON,
} from './AnnotationIntroduction'
import type { AnnotationNavigation } from './AnnotationNavigation'
import {
  instanceOfAnnotationNavigation,
  AnnotationNavigationFromJSON,
  AnnotationNavigationFromJSONTyped,
  AnnotationNavigationToJSON,
} from './AnnotationNavigation'
import type { AnnotationTransmission } from './AnnotationTransmission'
import {
  instanceOfAnnotationTransmission,
  AnnotationTransmissionFromJSON,
  AnnotationTransmissionFromJSONTyped,
  AnnotationTransmissionToJSON,
} from './AnnotationTransmission'

/**
 * @type AnnotationData
 *
 * @export
 */
export type AnnotationData = AnnotationIntroduction | AnnotationNavigation | AnnotationTransmission

export function AnnotationDataFromJSON(json: any): AnnotationData {
  return AnnotationDataFromJSONTyped(json, false)
}

export function AnnotationDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnnotationData {
  if (json == null) {
    return json
  }
  return (
    AnnotationIntroductionFromJSONTyped(json, true) ||
    AnnotationNavigationFromJSONTyped(json, true) ||
    AnnotationTransmissionFromJSONTyped(json, true)
  )
}

export function AnnotationDataToJSON(value?: AnnotationData | null): any {
  if (value == null) {
    return value
  }

  if (instanceOfAnnotationIntroduction(value)) {
    return AnnotationIntroductionToJSON(value as AnnotationIntroduction)
  }
  if (instanceOfAnnotationNavigation(value)) {
    return AnnotationNavigationToJSON(value as AnnotationNavigation)
  }
  if (instanceOfAnnotationTransmission(value)) {
    return AnnotationTransmissionToJSON(value as AnnotationTransmission)
  }

  return {}
}
