/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AnnotationData } from './AnnotationData'
import {
  AnnotationDataFromJSON,
  AnnotationDataFromJSONTyped,
  AnnotationDataToJSON,
} from './AnnotationData'

/**
 *
 * @export
 * @interface AnnotationResponse
 */
export interface AnnotationResponse {
  /**
   * ID 编号
   * @type {number}
   * @memberof AnnotationResponse
   */
  annotationId: number
  /**
   *
   * @type {number}
   * @memberof AnnotationResponse
   */
  sceneId: number
  /**
   *
   * @type {number}
   * @memberof AnnotationResponse
   */
  positionX: number
  /**
   *
   * @type {number}
   * @memberof AnnotationResponse
   */
  positionY: number
  /**
   *
   * @type {number}
   * @memberof AnnotationResponse
   */
  positionZ: number
  /**
   * 标记球体半径
   * @type {number}
   * @memberof AnnotationResponse
   */
  radius: number
  /**
   * 用字符串表示颜色，如"#FF0000"表示红色，需要验证字符串合法性
   * @type {string}
   * @memberof AnnotationResponse
   */
  color: string
  /**
   * 名称
   * @type {string}
   * @memberof AnnotationResponse
   */
  name: string
  /**
   *
   * @type {AnnotationData}
   * @memberof AnnotationResponse
   */
  annotationData: AnnotationData
}

/**
 * Check if a given object implements the AnnotationResponse interface.
 */
export function instanceOfAnnotationResponse(value: object): boolean {
  if (!('annotationId' in value)) return false
  if (!('sceneId' in value)) return false
  if (!('positionX' in value)) return false
  if (!('positionY' in value)) return false
  if (!('positionZ' in value)) return false
  if (!('radius' in value)) return false
  if (!('color' in value)) return false
  if (!('name' in value)) return false
  if (!('annotationData' in value)) return false
  return true
}

export function AnnotationResponseFromJSON(json: any): AnnotationResponse {
  return AnnotationResponseFromJSONTyped(json, false)
}

export function AnnotationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnnotationResponse {
  if (json == null) {
    return json
  }
  return {
    annotationId: json['annotationId'],
    sceneId: json['sceneId'],
    positionX: json['position_x'],
    positionY: json['position_y'],
    positionZ: json['position_z'],
    radius: json['radius'],
    color: json['color'],
    name: json['name'],
    annotationData: AnnotationDataFromJSON(json['annotationData']),
  }
}

export function AnnotationResponseToJSON(value?: AnnotationResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    annotationId: value['annotationId'],
    sceneId: value['sceneId'],
    position_x: value['positionX'],
    position_y: value['positionY'],
    position_z: value['positionZ'],
    radius: value['radius'],
    color: value['color'],
    name: value['name'],
    annotationData: AnnotationDataToJSON(value['annotationData']),
  }
}
