/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AudioResponse
 */
export interface AudioResponse {
  /**
   * 返还音频url，通常应该是cacheUrl
   * @type {string}
   * @memberof AudioResponse
   */
  audioUrl: string
}

/**
 * Check if a given object implements the AudioResponse interface.
 */
export function instanceOfAudioResponse(value: object): boolean {
  if (!('audioUrl' in value)) return false
  return true
}

export function AudioResponseFromJSON(json: any): AudioResponse {
  return AudioResponseFromJSONTyped(json, false)
}

export function AudioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioResponse {
  if (json == null) {
    return json
  }
  return {
    audioUrl: json['audioUrl'],
  }
}

export function AudioResponseToJSON(value?: AudioResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    audioUrl: value['audioUrl'],
  }
}
