/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CarouselImageResponse
 */
export interface CarouselImageResponse {
  /**
   * 轮播图id
   * @type {number}
   * @memberof CarouselImageResponse
   */
  carouselImageId: number
  /**
   * 添加人id
   * @type {number}
   * @memberof CarouselImageResponse
   */
  creatorId: number
  /**
   * 关联场景id
   * @type {number}
   * @memberof CarouselImageResponse
   */
  sceneId: number
  /**
   * 轮播图url
   * @type {string}
   * @memberof CarouselImageResponse
   */
  url: string
  /**
   * 图片的描述说明
   * @type {string}
   * @memberof CarouselImageResponse
   */
  caption?: string
  /**
   * 图片在轮播图里的显示顺序，为空，默认为最后一位
   * @type {number}
   * @memberof CarouselImageResponse
   */
  orderIndex?: number
}

/**
 * Check if a given object implements the CarouselImageResponse interface.
 */
export function instanceOfCarouselImageResponse(value: object): boolean {
  if (!('carouselImageId' in value)) return false
  if (!('creatorId' in value)) return false
  if (!('sceneId' in value)) return false
  if (!('url' in value)) return false
  return true
}

export function CarouselImageResponseFromJSON(json: any): CarouselImageResponse {
  return CarouselImageResponseFromJSONTyped(json, false)
}

export function CarouselImageResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CarouselImageResponse {
  if (json == null) {
    return json
  }
  return {
    carouselImageId: json['carouselImageId'],
    creatorId: json['creatorId'],
    sceneId: json['sceneId'],
    url: json['url'],
    caption: json['caption'] == null ? undefined : json['caption'],
    orderIndex: json['orderIndex'] == null ? undefined : json['orderIndex'],
  }
}

export function CarouselImageResponseToJSON(value?: CarouselImageResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    carouselImageId: value['carouselImageId'],
    creatorId: value['creatorId'],
    sceneId: value['sceneId'],
    url: value['url'],
    caption: value['caption'],
    orderIndex: value['orderIndex'],
  }
}
