/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CollabotatorRequest
 */
export interface CollabotatorRequest {
  /**
   * 协助者ID
   * @type {Array<number>}
   * @memberof CollabotatorRequest
   */
  targetCollaborators: Array<number>
  /**
   * 场景ID
   * @type {number}
   * @memberof CollabotatorRequest
   */
  sceneId: number
}

/**
 * Check if a given object implements the CollabotatorRequest interface.
 */
export function instanceOfCollabotatorRequest(value: object): boolean {
  if (!('targetCollaborators' in value)) return false
  if (!('sceneId' in value)) return false
  return true
}

export function CollabotatorRequestFromJSON(json: any): CollabotatorRequest {
  return CollabotatorRequestFromJSONTyped(json, false)
}

export function CollabotatorRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollabotatorRequest {
  if (json == null) {
    return json
  }
  return {
    targetCollaborators: json['targetCollaborators'],
    sceneId: json['sceneId'],
  }
}

export function CollabotatorRequestToJSON(value?: CollabotatorRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    targetCollaborators: value['targetCollaborators'],
    sceneId: value['sceneId'],
  }
}
