/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CollaboratorResponse
 */
export interface CollaboratorResponse {
  /**
   * 协助者ID 编号
   * @type {string}
   * @memberof CollaboratorResponse
   */
  id: string
  /**
   * 协助者名称
   * @type {string}
   * @memberof CollaboratorResponse
   */
  name: string
}

/**
 * Check if a given object implements the CollaboratorResponse interface.
 */
export function instanceOfCollaboratorResponse(value: object): boolean {
  if (!('id' in value)) return false
  if (!('name' in value)) return false
  return true
}

export function CollaboratorResponseFromJSON(json: any): CollaboratorResponse {
  return CollaboratorResponseFromJSONTyped(json, false)
}

export function CollaboratorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollaboratorResponse {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    name: json['name'],
  }
}

export function CollaboratorResponseToJSON(value?: CollaboratorResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value['id'],
    name: value['name'],
  }
}
