/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CoverResponse
 */
export interface CoverResponse {
  /**
   * 封面url
   * @type {string}
   * @memberof CoverResponse
   */
  url: string
  /**
   * 标题，使用对应场景名
   * @type {string}
   * @memberof CoverResponse
   */
  title: string
  /**
   * 发布者，使用对应场景的创作者ID或创作者名
   * @type {string}
   * @memberof CoverResponse
   */
  author: string
}

/**
 * Check if a given object implements the CoverResponse interface.
 */
export function instanceOfCoverResponse(value: object): boolean {
  if (!('url' in value)) return false
  if (!('title' in value)) return false
  if (!('author' in value)) return false
  return true
}

export function CoverResponseFromJSON(json: any): CoverResponse {
  return CoverResponseFromJSONTyped(json, false)
}

export function CoverResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverResponse {
  if (json == null) {
    return json
  }
  return {
    url: json['url'],
    title: json['title'],
    author: json['author'],
  }
}

export function CoverResponseToJSON(value?: CoverResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    url: value['url'],
    title: value['title'],
    author: value['author'],
  }
}
