/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateSceneRequest
 */
export interface CreateSceneRequest {
  /**
   * 场景名
   * @type {string}
   * @memberof CreateSceneRequest
   */
  name: string
  /**
   * 场景链接，Luma AI 的场景链接（如 `https://lumalabs.ai/capture/8575c740-88ce-4418-bd06-de06c51b2f3f`）
   * @type {string}
   * @memberof CreateSceneRequest
   */
  url: string
  /**
   * 场景描述
   * @type {string}
   * @memberof CreateSceneRequest
   */
  description?: string
  /**
   * 协作者id
   * @type {Array<number>}
   * @memberof CreateSceneRequest
   */
  collaboratorsId?: Array<number>
  /**
   * 标签tags
   * @type {Array<string>}
   * @memberof CreateSceneRequest
   */
  tags?: Array<string>
  /**
   * 调用 uploadImage 接口返回的临时图片链接
   * @type {string}
   * @memberof CreateSceneRequest
   */
  cacheImageUrl?: string
}

/**
 * Check if a given object implements the CreateSceneRequest interface.
 */
export function instanceOfCreateSceneRequest(value: object): boolean {
  if (!('name' in value)) return false
  if (!('url' in value)) return false
  return true
}

export function CreateSceneRequestFromJSON(json: any): CreateSceneRequest {
  return CreateSceneRequestFromJSONTyped(json, false)
}

export function CreateSceneRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSceneRequest {
  if (json == null) {
    return json
  }
  return {
    name: json['name'],
    url: json['url'],
    description: json['description'] == null ? undefined : json['description'],
    collaboratorsId: json['collaboratorsId'] == null ? undefined : json['collaboratorsId'],
    tags: json['tags'] == null ? undefined : json['tags'],
    cacheImageUrl: json['cacheImageUrl'] == null ? undefined : json['cacheImageUrl'],
  }
}

export function CreateSceneRequestToJSON(value?: CreateSceneRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    name: value['name'],
    url: value['url'],
    description: value['description'],
    collaboratorsId: value['collaboratorsId'],
    tags: value['tags'],
    cacheImageUrl: value['cacheImageUrl'],
  }
}
