/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { TagId } from './TagId'
import { TagIdFromJSON, TagIdFromJSONTyped, TagIdToJSON } from './TagId'

/**
 *
 * @export
 * @interface DeleteTagListRequest
 */
export interface DeleteTagListRequest {
  /**
   *
   * @type {Array<TagId>}
   * @memberof DeleteTagListRequest
   */
  tagList: Array<TagId>
}

/**
 * Check if a given object implements the DeleteTagListRequest interface.
 */
export function instanceOfDeleteTagListRequest(value: object): boolean {
  if (!('tagList' in value)) return false
  return true
}

export function DeleteTagListRequestFromJSON(json: any): DeleteTagListRequest {
  return DeleteTagListRequestFromJSONTyped(json, false)
}

export function DeleteTagListRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteTagListRequest {
  if (json == null) {
    return json
  }
  return {
    tagList: (json['tagList'] as Array<any>).map(TagIdFromJSON),
  }
}

export function DeleteTagListRequestToJSON(value?: DeleteTagListRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    tagList: (value['tagList'] as Array<any>).map(TagIdToJSON),
  }
}
