/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface DeleteUserResponse
 */
export interface DeleteUserResponse {
  /**
   *
   * @type {string}
   * @memberof DeleteUserResponse
   */
  message: string
}

/**
 * Check if a given object implements the DeleteUserResponse interface.
 */
export function instanceOfDeleteUserResponse(value: object): boolean {
  if (!('message' in value)) return false
  return true
}

export function DeleteUserResponseFromJSON(json: any): DeleteUserResponse {
  return DeleteUserResponseFromJSONTyped(json, false)
}

export function DeleteUserResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteUserResponse {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function DeleteUserResponseToJSON(value?: DeleteUserResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    message: value['message'],
  }
}
