/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface DeleteUser200Response
 */
export interface DeleteUser200Response {
  /**
   *
   * @type {string}
   * @memberof DeleteUser200Response
   */
  message: string
}

/**
 * Check if a given object implements the DeleteUser200Response interface.
 */
export function instanceOfDeleteUser200Response(value: object): boolean {
  if (!('message' in value)) return false
  return true
}

export function DeleteUser200ResponseFromJSON(json: any): DeleteUser200Response {
  return DeleteUser200ResponseFromJSONTyped(json, false)
}

export function DeleteUser200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteUser200Response {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function DeleteUser200ResponseToJSON(value?: DeleteUser200Response | null): any {
  if (value == null) {
    return value
  }
  return {
    message: value['message'],
  }
}
