/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Vector3 } from './Vector3'
import { Vector3FromJSON, Vector3FromJSONTyped, Vector3ToJSON } from './Vector3'

/**
 *
 * @export
 * @interface EditSceneRequest
 */
export interface EditSceneRequest {
  /**
   * 场景 ID
   * @type {number}
   * @memberof EditSceneRequest
   */
  id: number
  /**
   * 场景名
   * @type {string}
   * @memberof EditSceneRequest
   */
  name?: string
  /**
   * 场景的 Luma 链接，如 `https://lumalabs.ai/capture/8575c740-88ce-4418-bd06-de06c51b2f3f`
   * @type {string}
   * @memberof EditSceneRequest
   */
  url?: string
  /**
   * 场景描述
   * @type {string}
   * @memberof EditSceneRequest
   */
  description?: string
  /**
   * 场景是否公开可见
   * @type {boolean}
   * @memberof EditSceneRequest
   */
  isPublic?: boolean
  /**
   * 标签
   * @type {Array<string>}
   * @memberof EditSceneRequest
   */
  tags?: Array<string>
  /**
   *
   * @type {Array<number>}
   * @memberof EditSceneRequest
   */
  collaborators?: Array<number>
  /**
   * 从上传图片接口上传后，在这里使用
   * @type {string}
   * @memberof EditSceneRequest
   */
  cacheImageUrl?: string
  /**
   *
   * @type {Vector3}
   * @memberof EditSceneRequest
   */
  birthPosition?: Vector3
  /**
   *
   * @type {Vector3}
   * @memberof EditSceneRequest
   */
  birthRotation?: Vector3
}

/**
 * Check if a given object implements the EditSceneRequest interface.
 */
export function instanceOfEditSceneRequest(value: object): boolean {
  if (!('id' in value)) return false
  return true
}

export function EditSceneRequestFromJSON(json: any): EditSceneRequest {
  return EditSceneRequestFromJSONTyped(json, false)
}

export function EditSceneRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EditSceneRequest {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    name: json['name'] == null ? undefined : json['name'],
    url: json['url'] == null ? undefined : json['url'],
    description: json['description'] == null ? undefined : json['description'],
    isPublic: json['isPublic'] == null ? undefined : json['isPublic'],
    tags: json['tags'] == null ? undefined : json['tags'],
    collaborators: json['collaborators'] == null ? undefined : json['collaborators'],
    cacheImageUrl: json['cacheImageUrl'] == null ? undefined : json['cacheImageUrl'],
    birthPosition:
      json['birthPosition'] == null ? undefined : Vector3FromJSON(json['birthPosition']),
    birthRotation:
      json['birthRotation'] == null ? undefined : Vector3FromJSON(json['birthRotation']),
  }
}

export function EditSceneRequestToJSON(value?: EditSceneRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value['id'],
    name: value['name'],
    url: value['url'],
    description: value['description'],
    isPublic: value['isPublic'],
    tags: value['tags'],
    collaborators: value['collaborators'],
    cacheImageUrl: value['cacheImageUrl'],
    birthPosition: Vector3ToJSON(value['birthPosition']),
    birthRotation: Vector3ToJSON(value['birthRotation']),
  }
}
