/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AnnotationData } from './AnnotationData'
import {
  AnnotationDataFromJSON,
  AnnotationDataFromJSONTyped,
  AnnotationDataToJSON,
} from './AnnotationData'
import type { AnnotationType } from './AnnotationType'
import {
  AnnotationTypeFromJSON,
  AnnotationTypeFromJSONTyped,
  AnnotationTypeToJSON,
} from './AnnotationType'

/**
 *
 * @export
 * @interface EditAnnotationRequest
 */
export interface EditAnnotationRequest {
  /**
   *
   * @type {number}
   * @memberof EditAnnotationRequest
   */
  annotationId: number
  /**
   *
   * @type {AnnotationData}
   * @memberof EditAnnotationRequest
   */
  annotationData: AnnotationData
  /**
   *
   * @type {number}
   * @memberof EditAnnotationRequest
   */
  positionX?: number
  /**
   *
   * @type {number}
   * @memberof EditAnnotationRequest
   */
  positionY?: number
  /**
   *
   * @type {number}
   * @memberof EditAnnotationRequest
   */
  positionZ?: number
  /**
   *
   * @type {number}
   * @memberof EditAnnotationRequest
   */
  radius?: number
  /**
   * 用字符串表示颜色，如"#FF0000"表示红色，需要验证字符串合法性
   * @type {string}
   * @memberof EditAnnotationRequest
   */
  color?: string
  /**
   *
   * @type {AnnotationType}
   * @memberof EditAnnotationRequest
   */
  type?: AnnotationType
  /**
   *
   * @type {string}
   * @memberof EditAnnotationRequest
   */
  name?: string
}

/**
 * Check if a given object implements the EditAnnotationRequest interface.
 */
export function instanceOfEditAnnotationRequest(value: object): boolean {
  if (!('annotationId' in value)) return false
  if (!('annotationData' in value)) return false
  return true
}

export function EditAnnotationRequestFromJSON(json: any): EditAnnotationRequest {
  return EditAnnotationRequestFromJSONTyped(json, false)
}

export function EditAnnotationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EditAnnotationRequest {
  if (json == null) {
    return json
  }
  return {
    annotationId: json['annotationId'],
    annotationData: json['annotationData'],
    positionX: json['position_x'] == null ? undefined : json['position_x'],
    positionY: json['position_y'] == null ? undefined : json['position_y'],
    positionZ: json['position_z'] == null ? undefined : json['position_z'],
    radius: json['radius'] == null ? undefined : json['radius'],
    color: json['color'] == null ? undefined : json['color'],
    type: json['type'] == null ? undefined : AnnotationTypeFromJSON(json['type']),
    name: json['name'] == null ? undefined : json['name'],
  }
}

export function EditAnnotationRequestToJSON(value?: EditAnnotationRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    annotationId: value['annotationId'],
    annotationData: AnnotationDataToJSON(value['annotationData']),
    position_x: value['positionX'],
    position_y: value['positionY'],
    position_z: value['positionZ'],
    radius: value['radius'],
    color: value['color'],
    type: AnnotationTypeToJSON(value['type']),
    name: value['name'],
  }
}
