/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface EditCarouselImageList200Response
 */
export interface EditCarouselImageList200Response {
  /**
   *
   * @type {number}
   * @memberof EditCarouselImageList200Response
   */
  carouselImageId: number
  /**
   *
   * @type {number}
   * @memberof EditCarouselImageList200Response
   */
  creatorId: number
  /**
   *
   * @type {number}
   * @memberof EditCarouselImageList200Response
   */
  sceneId: number
  /**
   *
   * @type {string}
   * @memberof EditCarouselImageList200Response
   */
  url: string
  /**
   *
   * @type {string}
   * @memberof EditCarouselImageList200Response
   */
  caption?: string
  /**
   * 为空，默认为最后一位
   * @type {number}
   * @memberof EditCarouselImageList200Response
   */
  orderIndex?: number
}

/**
 * Check if a given object implements the EditCarouselImageList200Response interface.
 */
export function instanceOfEditCarouselImageList200Response(value: object): boolean {
  if (!('carouselImageId' in value)) return false
  if (!('creatorId' in value)) return false
  if (!('sceneId' in value)) return false
  if (!('url' in value)) return false
  return true
}

export function EditCarouselImageList200ResponseFromJSON(
  json: any,
): EditCarouselImageList200Response {
  return EditCarouselImageList200ResponseFromJSONTyped(json, false)
}

export function EditCarouselImageList200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EditCarouselImageList200Response {
  if (json == null) {
    return json
  }
  return {
    carouselImageId: json['carouselImageId'],
    creatorId: json['creatorId'],
    sceneId: json['sceneId'],
    url: json['url'],
    caption: json['caption'] == null ? undefined : json['caption'],
    orderIndex: json['orderIndex'] == null ? undefined : json['orderIndex'],
  }
}

export function EditCarouselImageList200ResponseToJSON(
  value?: EditCarouselImageList200Response | null,
): any {
  if (value == null) {
    return value
  }
  return {
    carouselImageId: value['carouselImageId'],
    creatorId: value['creatorId'],
    sceneId: value['sceneId'],
    url: value['url'],
    caption: value['caption'],
    orderIndex: value['orderIndex'],
  }
}
