/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface EditCarouselImageRequest
 */
export interface EditCarouselImageRequest {
  /**
   * 轮播图id
   * @type {number}
   * @memberof EditCarouselImageRequest
   */
  carouselImageId: number
  /**
   * 场景id
   * @type {number}
   * @memberof EditCarouselImageRequest
   */
  sceneId?: number
  /**
   * 轮播图的url
   * @type {string}
   * @memberof EditCarouselImageRequest
   */
  imageUrl?: string
  /**
   * 图片的描述说明
   * @type {string}
   * @memberof EditCarouselImageRequest
   */
  caption?: string
  /**
   * 图片在轮播图里的显示顺序
   * @type {number}
   * @memberof EditCarouselImageRequest
   */
  orderIndex?: number
}

/**
 * Check if a given object implements the EditCarouselImageRequest interface.
 */
export function instanceOfEditCarouselImageRequest(value: object): boolean {
  if (!('carouselImageId' in value)) return false
  return true
}

export function EditCarouselImageRequestFromJSON(json: any): EditCarouselImageRequest {
  return EditCarouselImageRequestFromJSONTyped(json, false)
}

export function EditCarouselImageRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EditCarouselImageRequest {
  if (json == null) {
    return json
  }
  return {
    carouselImageId: json['carouselImageId'],
    sceneId: json['sceneId'] == null ? undefined : json['sceneId'],
    imageUrl: json['imageUrl'] == null ? undefined : json['imageUrl'],
    caption: json['caption'] == null ? undefined : json['caption'],
    orderIndex: json['orderIndex'] == null ? undefined : json['orderIndex'],
  }
}

export function EditCarouselImageRequestToJSON(value?: EditCarouselImageRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    carouselImageId: value['carouselImageId'],
    sceneId: value['sceneId'],
    imageUrl: value['imageUrl'],
    caption: value['caption'],
    orderIndex: value['orderIndex'],
  }
}
