/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface EditSceneAnnotationIntroduction
 */
export interface EditSceneAnnotationIntroduction {
  /**
   * ID 编号
   * @type {number}
   * @memberof EditSceneAnnotationIntroduction
   */
  sceneAnnotationIntroductionId: number
  /**
   *
   * @type {string}
   * @memberof EditSceneAnnotationIntroduction
   */
  introduction: string
}

/**
 * Check if a given object implements the EditSceneAnnotationIntroduction interface.
 */
export function instanceOfEditSceneAnnotationIntroduction(value: object): boolean {
  if (!('sceneAnnotationIntroductionId' in value)) return false
  if (!('introduction' in value)) return false
  return true
}

export function EditSceneAnnotationIntroductionFromJSON(
  json: any,
): EditSceneAnnotationIntroduction {
  return EditSceneAnnotationIntroductionFromJSONTyped(json, false)
}

export function EditSceneAnnotationIntroductionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EditSceneAnnotationIntroduction {
  if (json == null) {
    return json
  }
  return {
    sceneAnnotationIntroductionId: json['sceneAnnotationIntroductionId'],
    introduction: json['introduction'],
  }
}

export function EditSceneAnnotationIntroductionToJSON(
  value?: EditSceneAnnotationIntroduction | null,
): any {
  if (value == null) {
    return value
  }
  return {
    sceneAnnotationIntroductionId: value['sceneAnnotationIntroductionId'],
    introduction: value['introduction'],
  }
}
