/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FavouritesCrudRequestBodyOneOf } from './FavouritesCrudRequestBodyOneOf'
import {
  instanceOfFavouritesCrudRequestBodyOneOf,
  FavouritesCrudRequestBodyOneOfFromJSON,
  FavouritesCrudRequestBodyOneOfFromJSONTyped,
  FavouritesCrudRequestBodyOneOfToJSON,
} from './FavouritesCrudRequestBodyOneOf'
import type { FavouritesCrudRequestBodyOneOf1 } from './FavouritesCrudRequestBodyOneOf1'
import {
  instanceOfFavouritesCrudRequestBodyOneOf1,
  FavouritesCrudRequestBodyOneOf1FromJSON,
  FavouritesCrudRequestBodyOneOf1FromJSONTyped,
  FavouritesCrudRequestBodyOneOf1ToJSON,
} from './FavouritesCrudRequestBodyOneOf1'
import type { FavouritesCrudRequestBodyOneOf2 } from './FavouritesCrudRequestBodyOneOf2'
import {
  instanceOfFavouritesCrudRequestBodyOneOf2,
  FavouritesCrudRequestBodyOneOf2FromJSON,
  FavouritesCrudRequestBodyOneOf2FromJSONTyped,
  FavouritesCrudRequestBodyOneOf2ToJSON,
} from './FavouritesCrudRequestBodyOneOf2'

/**
 * @type FavouritesCrudRequestBody
 *
 * @export
 */
export type FavouritesCrudRequestBody =
  | FavouritesCrudRequestBodyOneOf
  | FavouritesCrudRequestBodyOneOf1
  | FavouritesCrudRequestBodyOneOf2

export function FavouritesCrudRequestBodyFromJSON(json: any): FavouritesCrudRequestBody {
  return FavouritesCrudRequestBodyFromJSONTyped(json, false)
}

export function FavouritesCrudRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavouritesCrudRequestBody {
  if (json == null) {
    return json
  }
  return (
    FavouritesCrudRequestBodyOneOfFromJSONTyped(json, true) ||
    FavouritesCrudRequestBodyOneOf1FromJSONTyped(json, true) ||
    FavouritesCrudRequestBodyOneOf2FromJSONTyped(json, true)
  )
}

export function FavouritesCrudRequestBodyToJSON(value?: FavouritesCrudRequestBody | null): any {
  if (value == null) {
    return value
  }

  if (instanceOfFavouritesCrudRequestBodyOneOf(value)) {
    return FavouritesCrudRequestBodyOneOfToJSON(value as FavouritesCrudRequestBodyOneOf)
  }
  if (instanceOfFavouritesCrudRequestBodyOneOf1(value)) {
    return FavouritesCrudRequestBodyOneOf1ToJSON(value as FavouritesCrudRequestBodyOneOf1)
  }
  if (instanceOfFavouritesCrudRequestBodyOneOf2(value)) {
    return FavouritesCrudRequestBodyOneOf2ToJSON(value as FavouritesCrudRequestBodyOneOf2)
  }

  return {}
}
