/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { FavouritesCrudRequestBody } from './FavouritesCrudRequestBody'
import {
  FavouritesCrudRequestBodyFromJSON,
  FavouritesCrudRequestBodyFromJSONTyped,
  FavouritesCrudRequestBodyToJSON,
} from './FavouritesCrudRequestBody'
import type { OperationType } from './OperationType'
import {
  OperationTypeFromJSON,
  OperationTypeFromJSONTyped,
  OperationTypeToJSON,
} from './OperationType'

/**
 *
 * @export
 * @interface FavouritesCrudRequest
 */
export interface FavouritesCrudRequest {
  /**
   *
   * @type {OperationType}
   * @memberof FavouritesCrudRequest
   */
  operation: OperationType
  /**
   *
   * @type {FavouritesCrudRequestBody}
   * @memberof FavouritesCrudRequest
   */
  body: FavouritesCrudRequestBody | null
}

/**
 * Check if a given object implements the FavouritesCrudRequest interface.
 */
export function instanceOfFavouritesCrudRequest(value: object): boolean {
  if (!('operation' in value)) return false
  if (!('body' in value)) return false
  return true
}

export function FavouritesCrudRequestFromJSON(json: any): FavouritesCrudRequest {
  return FavouritesCrudRequestFromJSONTyped(json, false)
}

export function FavouritesCrudRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavouritesCrudRequest {
  if (json == null) {
    return json
  }
  return {
    operation: OperationTypeFromJSON(json['operation']),
    body: FavouritesCrudRequestBodyFromJSON(json['body']),
  }
}

export function FavouritesCrudRequestToJSON(value?: FavouritesCrudRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    operation: OperationTypeToJSON(value['operation']),
    body: FavouritesCrudRequestBodyToJSON(value['body']),
  }
}
