/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FavoriteSceneCrudRequestBodyOneOf } from './FavoriteSceneCrudRequestBodyOneOf'
import {
  instanceOfFavoriteSceneCrudRequestBodyOneOf,
  FavoriteSceneCrudRequestBodyOneOfFromJSON,
  FavoriteSceneCrudRequestBodyOneOfFromJSONTyped,
  FavoriteSceneCrudRequestBodyOneOfToJSON,
} from './FavoriteSceneCrudRequestBodyOneOf'
import type { FavoriteSceneCrudRequestBodyOneOf1 } from './FavoriteSceneCrudRequestBodyOneOf1'
import {
  instanceOfFavoriteSceneCrudRequestBodyOneOf1,
  FavoriteSceneCrudRequestBodyOneOf1FromJSON,
  FavoriteSceneCrudRequestBodyOneOf1FromJSONTyped,
  FavoriteSceneCrudRequestBodyOneOf1ToJSON,
} from './FavoriteSceneCrudRequestBodyOneOf1'
import type { FavoriteSceneCrudRequestBodyOneOf2 } from './FavoriteSceneCrudRequestBodyOneOf2'
import {
  instanceOfFavoriteSceneCrudRequestBodyOneOf2,
  FavoriteSceneCrudRequestBodyOneOf2FromJSON,
  FavoriteSceneCrudRequestBodyOneOf2FromJSONTyped,
  FavoriteSceneCrudRequestBodyOneOf2ToJSON,
} from './FavoriteSceneCrudRequestBodyOneOf2'
import type { FavoriteSceneCrudRequestBodyOneOf3 } from './FavoriteSceneCrudRequestBodyOneOf3'
import {
  instanceOfFavoriteSceneCrudRequestBodyOneOf3,
  FavoriteSceneCrudRequestBodyOneOf3FromJSON,
  FavoriteSceneCrudRequestBodyOneOf3FromJSONTyped,
  FavoriteSceneCrudRequestBodyOneOf3ToJSON,
} from './FavoriteSceneCrudRequestBodyOneOf3'

/**
 * @type FavoriteSceneCrudRequestBody
 *
 * @export
 */
export type FavoriteSceneCrudRequestBody =
  | FavoriteSceneCrudRequestBodyOneOf
  | FavoriteSceneCrudRequestBodyOneOf1
  | FavoriteSceneCrudRequestBodyOneOf2
  | FavoriteSceneCrudRequestBodyOneOf3

export function FavoriteSceneCrudRequestBodyFromJSON(json: any): FavoriteSceneCrudRequestBody {
  return FavoriteSceneCrudRequestBodyFromJSONTyped(json, false)
}

export function FavoriteSceneCrudRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavoriteSceneCrudRequestBody {
  if (json == null) {
    return json
  }
  return (
    FavoriteSceneCrudRequestBodyOneOfFromJSONTyped(json, true) ||
    FavoriteSceneCrudRequestBodyOneOf1FromJSONTyped(json, true) ||
    FavoriteSceneCrudRequestBodyOneOf2FromJSONTyped(json, true) ||
    FavoriteSceneCrudRequestBodyOneOf3FromJSONTyped(json, true)
  )
}

export function FavoriteSceneCrudRequestBodyToJSON(
  value?: FavoriteSceneCrudRequestBody | null,
): any {
  if (value == null) {
    return value
  }

  if (instanceOfFavoriteSceneCrudRequestBodyOneOf(value)) {
    return FavoriteSceneCrudRequestBodyOneOfToJSON(value as FavoriteSceneCrudRequestBodyOneOf)
  }
  if (instanceOfFavoriteSceneCrudRequestBodyOneOf1(value)) {
    return FavoriteSceneCrudRequestBodyOneOf1ToJSON(value as FavoriteSceneCrudRequestBodyOneOf1)
  }
  if (instanceOfFavoriteSceneCrudRequestBodyOneOf2(value)) {
    return FavoriteSceneCrudRequestBodyOneOf2ToJSON(value as FavoriteSceneCrudRequestBodyOneOf2)
  }
  if (instanceOfFavoriteSceneCrudRequestBodyOneOf3(value)) {
    return FavoriteSceneCrudRequestBodyOneOf3ToJSON(value as FavoriteSceneCrudRequestBodyOneOf3)
  }

  return {}
}
