/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * delete
 * @export
 * @interface FavouritesCrudRequestBodyOneOf2
 */
export interface FavouritesCrudRequestBodyOneOf2 {
  /**
   *
   * @type {string}
   * @memberof FavouritesCrudRequestBodyOneOf2
   */
  existingFavouritesName: string
}

/**
 * Check if a given object implements the FavouritesCrudRequestBodyOneOf2 interface.
 */
export function instanceOfFavouritesCrudRequestBodyOneOf2(value: object): boolean {
  if (!('existingFavouritesName' in value)) return false
  return true
}

export function FavouritesCrudRequestBodyOneOf2FromJSON(
  json: any,
): FavouritesCrudRequestBodyOneOf2 {
  return FavouritesCrudRequestBodyOneOf2FromJSONTyped(json, false)
}

export function FavouritesCrudRequestBodyOneOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavouritesCrudRequestBodyOneOf2 {
  if (json == null) {
    return json
  }
  return {
    existingFavouritesName: json['existingFavouritesName'],
  }
}

export function FavouritesCrudRequestBodyOneOf2ToJSON(
  value?: FavouritesCrudRequestBodyOneOf2 | null,
): any {
  if (value == null) {
    return value
  }
  return {
    existingFavouritesName: value['existingFavouritesName'],
  }
}
