/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * update
 * @export
 * @interface FavouritesCrudRequestBodyOneOf1
 */
export interface FavouritesCrudRequestBodyOneOf1 {
  /**
   *
   * @type {string}
   * @memberof FavouritesCrudRequestBodyOneOf1
   */
  existingFavouritesName: string
  /**
   *
   * @type {string}
   * @memberof FavouritesCrudRequestBodyOneOf1
   */
  newFavouritesName: string
}

/**
 * Check if a given object implements the FavouritesCrudRequestBodyOneOf1 interface.
 */
export function instanceOfFavouritesCrudRequestBodyOneOf1(value: object): boolean {
  if (!('existingFavouritesName' in value)) return false
  if (!('newFavouritesName' in value)) return false
  return true
}

export function FavouritesCrudRequestBodyOneOf1FromJSON(
  json: any,
): FavouritesCrudRequestBodyOneOf1 {
  return FavouritesCrudRequestBodyOneOf1FromJSONTyped(json, false)
}

export function FavouritesCrudRequestBodyOneOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavouritesCrudRequestBodyOneOf1 {
  if (json == null) {
    return json
  }
  return {
    existingFavouritesName: json['existingFavouritesName'],
    newFavouritesName: json['newFavouritesName'],
  }
}

export function FavouritesCrudRequestBodyOneOf1ToJSON(
  value?: FavouritesCrudRequestBodyOneOf1 | null,
): any {
  if (value == null) {
    return value
  }
  return {
    existingFavouritesName: value['existingFavouritesName'],
    newFavouritesName: value['newFavouritesName'],
  }
}
