/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * create
 * @export
 * @interface FavoriteSceneCrudRequestBodyOneOf
 */
export interface FavoriteSceneCrudRequestBodyOneOf {
  /**
   *
   * @type {string}
   * @memberof FavoriteSceneCrudRequestBodyOneOf
   */
  existingFavouritesName: string
  /**
   *
   * @type {number}
   * @memberof FavoriteSceneCrudRequestBodyOneOf
   */
  sceneId: number
}

/**
 * Check if a given object implements the FavoriteSceneCrudRequestBodyOneOf interface.
 */
export function instanceOfFavoriteSceneCrudRequestBodyOneOf(value: object): boolean {
  if (!('existingFavouritesName' in value)) return false
  if (!('sceneId' in value)) return false
  return true
}

export function FavoriteSceneCrudRequestBodyOneOfFromJSON(
  json: any,
): FavoriteSceneCrudRequestBodyOneOf {
  return FavoriteSceneCrudRequestBodyOneOfFromJSONTyped(json, false)
}

export function FavoriteSceneCrudRequestBodyOneOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavoriteSceneCrudRequestBodyOneOf {
  if (json == null) {
    return json
  }
  return {
    existingFavouritesName: json['existingFavouritesName'],
    sceneId: json['sceneId'],
  }
}

export function FavoriteSceneCrudRequestBodyOneOfToJSON(
  value?: FavoriteSceneCrudRequestBodyOneOf | null,
): any {
  if (value == null) {
    return value
  }
  return {
    existingFavouritesName: value['existingFavouritesName'],
    sceneId: value['sceneId'],
  }
}
