/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { FavoriteSceneCrudRequestBody } from './FavoriteSceneCrudRequestBody'
import {
  FavoriteSceneCrudRequestBodyFromJSON,
  FavoriteSceneCrudRequestBodyFromJSONTyped,
  FavoriteSceneCrudRequestBodyToJSON,
} from './FavoriteSceneCrudRequestBody'
import type { OperationType } from './OperationType'
import {
  OperationTypeFromJSON,
  OperationTypeFromJSONTyped,
  OperationTypeToJSON,
} from './OperationType'

/**
 *
 * @export
 * @interface FavoriteSceneCrudRequest
 */
export interface FavoriteSceneCrudRequest {
  /**
   *
   * @type {OperationType}
   * @memberof FavoriteSceneCrudRequest
   */
  operation: OperationType
  /**
   *
   * @type {FavoriteSceneCrudRequestBody}
   * @memberof FavoriteSceneCrudRequest
   */
  body: FavoriteSceneCrudRequestBody
}

/**
 * Check if a given object implements the FavoriteSceneCrudRequest interface.
 */
export function instanceOfFavoriteSceneCrudRequest(value: object): boolean {
  if (!('operation' in value)) return false
  if (!('body' in value)) return false
  return true
}

export function FavoriteSceneCrudRequestFromJSON(json: any): FavoriteSceneCrudRequest {
  return FavoriteSceneCrudRequestFromJSONTyped(json, false)
}

export function FavoriteSceneCrudRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavoriteSceneCrudRequest {
  if (json == null) {
    return json
  }
  return {
    operation: OperationTypeFromJSON(json['operation']),
    body: FavoriteSceneCrudRequestBodyFromJSON(json['body']),
  }
}

export function FavoriteSceneCrudRequestToJSON(value?: FavoriteSceneCrudRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    operation: OperationTypeToJSON(value['operation']),
    body: FavoriteSceneCrudRequestBodyToJSON(value['body']),
  }
}
