/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface FavoriteListResponse
 */
export interface FavoriteListResponse {
  /**
   *
   * @type {number}
   * @memberof FavoriteListResponse
   */
  totalCount: number
  /**
   * 收集场景ID列表
   * @type {Array<number>}
   * @memberof FavoriteListResponse
   */
  favoriteList: Array<number>
}

/**
 * Check if a given object implements the FavoriteListResponse interface.
 */
export function instanceOfFavoriteListResponse(value: object): boolean {
  if (!('totalCount' in value)) return false
  if (!('favoriteList' in value)) return false
  return true
}

export function FavoriteListResponseFromJSON(json: any): FavoriteListResponse {
  return FavoriteListResponseFromJSONTyped(json, false)
}

export function FavoriteListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavoriteListResponse {
  if (json == null) {
    return json
  }
  return {
    totalCount: json['totalCount'],
    favoriteList: json['favoriteList'],
  }
}

export function FavoriteListResponseToJSON(value?: FavoriteListResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    totalCount: value['totalCount'],
    favoriteList: value['favoriteList'],
  }
}
