/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * create
 * @export
 * @interface FavouritesCrudRequestBodyOneOf
 */
export interface FavouritesCrudRequestBodyOneOf {
  /**
   *
   * @type {string}
   * @memberof FavouritesCrudRequestBodyOneOf
   */
  newFavouritesName: string
}

/**
 * Check if a given object implements the FavouritesCrudRequestBodyOneOf interface.
 */
export function instanceOfFavouritesCrudRequestBodyOneOf(value: object): boolean {
  if (!('newFavouritesName' in value)) return false
  return true
}

export function FavouritesCrudRequestBodyOneOfFromJSON(json: any): FavouritesCrudRequestBodyOneOf {
  return FavouritesCrudRequestBodyOneOfFromJSONTyped(json, false)
}

export function FavouritesCrudRequestBodyOneOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavouritesCrudRequestBodyOneOf {
  if (json == null) {
    return json
  }
  return {
    newFavouritesName: json['newFavouritesName'],
  }
}

export function FavouritesCrudRequestBodyOneOfToJSON(
  value?: FavouritesCrudRequestBodyOneOf | null,
): any {
  if (value == null) {
    return value
  }
  return {
    newFavouritesName: value['newFavouritesName'],
  }
}
