/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * read
 * @export
 * @interface FavoriteSceneCrudRequestBodyOneOf1
 */
export interface FavoriteSceneCrudRequestBodyOneOf1 {
  /**
   *
   * @type {string}
   * @memberof FavoriteSceneCrudRequestBodyOneOf1
   */
  existingFavouritesName: string
}

/**
 * Check if a given object implements the FavoriteSceneCrudRequestBodyOneOf1 interface.
 */
export function instanceOfFavoriteSceneCrudRequestBodyOneOf1(value: object): boolean {
  if (!('existingFavouritesName' in value)) return false
  return true
}

export function FavoriteSceneCrudRequestBodyOneOf1FromJSON(
  json: any,
): FavoriteSceneCrudRequestBodyOneOf1 {
  return FavoriteSceneCrudRequestBodyOneOf1FromJSONTyped(json, false)
}

export function FavoriteSceneCrudRequestBodyOneOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavoriteSceneCrudRequestBodyOneOf1 {
  if (json == null) {
    return json
  }
  return {
    existingFavouritesName: json['existingFavouritesName'],
  }
}

export function FavoriteSceneCrudRequestBodyOneOf1ToJSON(
  value?: FavoriteSceneCrudRequestBodyOneOf1 | null,
): any {
  if (value == null) {
    return value
  }
  return {
    existingFavouritesName: value['existingFavouritesName'],
  }
}
