/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * update
 * @export
 * @interface FavoriteSceneCrudRequestBodyOneOf3
 */
export interface FavoriteSceneCrudRequestBodyOneOf3 {
  /**
   *
   * @type {string}
   * @memberof FavoriteSceneCrudRequestBodyOneOf3
   */
  existingFavouritesName: string
  /**
   *
   * @type {Array<number>}
   * @memberof FavoriteSceneCrudRequestBodyOneOf3
   */
  sceneIdList: Array<number>
}

/**
 * Check if a given object implements the FavoriteSceneCrudRequestBodyOneOf3 interface.
 */
export function instanceOfFavoriteSceneCrudRequestBodyOneOf3(value: object): boolean {
  if (!('existingFavouritesName' in value)) return false
  if (!('sceneIdList' in value)) return false
  return true
}

export function FavoriteSceneCrudRequestBodyOneOf3FromJSON(
  json: any,
): FavoriteSceneCrudRequestBodyOneOf3 {
  return FavoriteSceneCrudRequestBodyOneOf3FromJSONTyped(json, false)
}

export function FavoriteSceneCrudRequestBodyOneOf3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavoriteSceneCrudRequestBodyOneOf3 {
  if (json == null) {
    return json
  }
  return {
    existingFavouritesName: json['existingFavouritesName'],
    sceneIdList: json['sceneIdList'],
  }
}

export function FavoriteSceneCrudRequestBodyOneOf3ToJSON(
  value?: FavoriteSceneCrudRequestBodyOneOf3 | null,
): any {
  if (value == null) {
    return value
  }
  return {
    existingFavouritesName: value['existingFavouritesName'],
    sceneIdList: value['sceneIdList'],
  }
}
