/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface FavouritesListResponse
 */
export interface FavouritesListResponse {
  /**
   *
   * @type {number}
   * @memberof FavouritesListResponse
   */
  totalCount: number
  /**
   *
   * @type {Array<string>}
   * @memberof FavouritesListResponse
   */
  favouritesList: Array<string>
}

/**
 * Check if a given object implements the FavouritesListResponse interface.
 */
export function instanceOfFavouritesListResponse(value: object): boolean {
  if (!('totalCount' in value)) return false
  if (!('favouritesList' in value)) return false
  return true
}

export function FavouritesListResponseFromJSON(json: any): FavouritesListResponse {
  return FavouritesListResponseFromJSONTyped(json, false)
}

export function FavouritesListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavouritesListResponse {
  if (json == null) {
    return json
  }
  return {
    totalCount: json['totalCount'],
    favouritesList: json['favouritesList'],
  }
}

export function FavouritesListResponseToJSON(value?: FavouritesListResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    totalCount: value['totalCount'],
    favouritesList: value['favouritesList'],
  }
}
