/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { TopSceneId } from './TopSceneId'
import { TopSceneIdFromJSON, TopSceneIdFromJSONTyped, TopSceneIdToJSON } from './TopSceneId'
import type { UserRole } from './UserRole'
import { UserRoleFromJSON, UserRoleFromJSONTyped, UserRoleToJSON } from './UserRole'

/**
 *
 * @export
 * @interface GetUserInfoResponse
 */
export interface GetUserInfoResponse {
  /**
   * 用户 ID
   * @type {number}
   * @memberof GetUserInfoResponse
   */
  id: number
  /**
   *
   * @type {UserRole}
   * @memberof GetUserInfoResponse
   */
  role: UserRole
  /**
   * 用户名称
   * @type {string}
   * @memberof GetUserInfoResponse
   */
  name?: string
  /**
   * 头像url
   * @type {string}
   * @memberof GetUserInfoResponse
   */
  avatarUrl?: string
  /**
   * 昵称
   * @type {string}
   * @memberof GetUserInfoResponse
   */
  nickName?: string
  /**
   * 签名
   * @type {string}
   * @memberof GetUserInfoResponse
   */
  motto?: string
  /**
   * 性别
   * @type {string}
   * @memberof GetUserInfoResponse
   */
  gender?: GetUserInfoResponseGenderV4Compat
  /**
   * 生日
   * @type {string}
   * @memberof GetUserInfoResponse
   */
  birthday?: string
  /**
   * 地址
   * @type {string}
   * @memberof GetUserInfoResponse
   */
  address?: string
  /**
   * 置顶场景id列表
   * @type {Array<TopSceneId>}
   * @memberof GetUserInfoResponse
   */
  topSceneIdList?: Array<TopSceneId>
}

/**
 * @export
 */
export const GetUserInfoResponseGenderV4Compat = {
  Male: 'male',
  Female: 'female',
  Unkown: 'unkown',
} as const
export type GetUserInfoResponseGenderV4Compat =
  (typeof GetUserInfoResponseGenderV4Compat)[keyof typeof GetUserInfoResponseGenderV4Compat]

/**
 * Check if a given object implements the GetUserInfoResponse interface.
 */
export function instanceOfGetUserInfoResponse(value: object): boolean {
  if (!('id' in value)) return false
  if (!('role' in value)) return false
  return true
}

export function GetUserInfoResponseFromJSON(json: any): GetUserInfoResponse {
  return GetUserInfoResponseFromJSONTyped(json, false)
}

export function GetUserInfoResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserInfoResponse {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    role: UserRoleFromJSON(json['role']),
    name: json['name'] == null ? undefined : json['name'],
    avatarUrl: json['avatarUrl'] == null ? undefined : json['avatarUrl'],
    nickName: json['nickName'] == null ? undefined : json['nickName'],
    motto: json['motto'] == null ? undefined : json['motto'],
    gender: json['gender'] == null ? undefined : json['gender'],
    birthday: json['birthday'] == null ? undefined : json['birthday'],
    address: json['address'] == null ? undefined : json['address'],
    topSceneIdList:
      json['topSceneIdList'] == null
        ? undefined
        : (json['topSceneIdList'] as Array<any>).map(TopSceneIdFromJSON),
  }
}

export function GetUserInfoResponseToJSON(value?: GetUserInfoResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value['id'],
    role: UserRoleToJSON(value['role']),
    name: value['name'],
    avatarUrl: value['avatarUrl'],
    nickName: value['nickName'],
    motto: value['motto'],
    gender: value['gender'],
    birthday: value['birthday'],
    address: value['address'],
    topSceneIdList:
      value['topSceneIdList'] == null
        ? undefined
        : (value['topSceneIdList'] as Array<any>).map(TopSceneIdToJSON),
  }
}
