/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface LikedScene200Response
 */
export interface LikedScene200Response {
  /**
   * 场景id
   * @type {number}
   * @memberof LikedScene200Response
   */
  sceneId: number
  /**
   * 用户id
   * @type {number}
   * @memberof LikedScene200Response
   */
  userId: number
  /**
   * 是否点赞
   * @type {boolean}
   * @memberof LikedScene200Response
   */
  isLiked: boolean
  /**
   * 当前场景点赞总数
   * @type {number}
   * @memberof LikedScene200Response
   */
  sceneLikedCount: number
}

/**
 * Check if a given object implements the LikedScene200Response interface.
 */
export function instanceOfLikedScene200Response(value: object): boolean {
  if (!('sceneId' in value)) return false
  if (!('userId' in value)) return false
  if (!('isLiked' in value)) return false
  if (!('sceneLikedCount' in value)) return false
  return true
}

export function LikedScene200ResponseFromJSON(json: any): LikedScene200Response {
  return LikedScene200ResponseFromJSONTyped(json, false)
}

export function LikedScene200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LikedScene200Response {
  if (json == null) {
    return json
  }
  return {
    sceneId: json['sceneId'],
    userId: json['userId'],
    isLiked: json['isLiked'],
    sceneLikedCount: json['sceneLikedCount'],
  }
}

export function LikedScene200ResponseToJSON(value?: LikedScene200Response | null): any {
  if (value == null) {
    return value
  }
  return {
    sceneId: value['sceneId'],
    userId: value['userId'],
    isLiked: value['isLiked'],
    sceneLikedCount: value['sceneLikedCount'],
  }
}
