/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface LikedResponse
 */
export interface LikedResponse {
  /**
   * 场景id
   * @type {number}
   * @memberof LikedResponse
   */
  sceneId: number
  /**
   * 用户id
   * @type {number}
   * @memberof LikedResponse
   */
  userId: number
  /**
   * 是否点赞
   * @type {boolean}
   * @memberof LikedResponse
   */
  isLiked: boolean
  /**
   * 当前场景点赞总数
   * @type {number}
   * @memberof LikedResponse
   */
  sceneLikedCount: number
}

/**
 * Check if a given object implements the LikedResponse interface.
 */
export function instanceOfLikedResponse(value: object): boolean {
  if (!('sceneId' in value)) return false
  if (!('userId' in value)) return false
  if (!('isLiked' in value)) return false
  if (!('sceneLikedCount' in value)) return false
  return true
}

export function LikedResponseFromJSON(json: any): LikedResponse {
  return LikedResponseFromJSONTyped(json, false)
}

export function LikedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikedResponse {
  if (json == null) {
    return json
  }
  return {
    sceneId: json['sceneId'],
    userId: json['userId'],
    isLiked: json['isLiked'],
    sceneLikedCount: json['sceneLikedCount'],
  }
}

export function LikedResponseToJSON(value?: LikedResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    sceneId: value['sceneId'],
    userId: value['userId'],
    isLiked: value['isLiked'],
    sceneLikedCount: value['sceneLikedCount'],
  }
}
