/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface LikeSceneRequest
 */
export interface LikeSceneRequest {
  /**
   *
   * @type {number}
   * @memberof LikeSceneRequest
   */
  sceneId: number
  /**
   *
   * @type {string}
   * @memberof LikeSceneRequest
   */
  operationType: LikeSceneRequestOperationTypeV4Compat
}

/**
 * @export
 */
export const LikeSceneRequestOperationTypeV4Compat = {
  Like: 'like',
  Dislike: 'dislike',
  Read: 'read',
} as const
export type LikeSceneRequestOperationTypeV4Compat =
  (typeof LikeSceneRequestOperationTypeV4Compat)[keyof typeof LikeSceneRequestOperationTypeV4Compat]

/**
 * Check if a given object implements the LikeSceneRequest interface.
 */
export function instanceOfLikeSceneRequest(value: object): boolean {
  if (!('sceneId' in value)) return false
  if (!('operationType' in value)) return false
  return true
}

export function LikeSceneRequestFromJSON(json: any): LikeSceneRequest {
  return LikeSceneRequestFromJSONTyped(json, false)
}

export function LikeSceneRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LikeSceneRequest {
  if (json == null) {
    return json
  }
  return {
    sceneId: json['sceneId'],
    operationType: json['operationType'],
  }
}

export function LikeSceneRequestToJSON(value?: LikeSceneRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    sceneId: value['sceneId'],
    operationType: value['operationType'],
  }
}
