/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Line
 */
export interface Line {
  /**
   * x坐标
   * @type {number}
   * @memberof Line
   */
  positionX: number
  /**
   * y坐标
   * @type {number}
   * @memberof Line
   */
  positionY: number
  /**
   * z坐标
   * @type {number}
   * @memberof Line
   */
  positionZ: number
}

/**
 * Check if a given object implements the Line interface.
 */
export function instanceOfLine(value: object): boolean {
  if (!('positionX' in value)) return false
  if (!('positionY' in value)) return false
  if (!('positionZ' in value)) return false
  return true
}

export function LineFromJSON(json: any): Line {
  return LineFromJSONTyped(json, false)
}

export function LineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Line {
  if (json == null) {
    return json
  }
  return {
    positionX: json['position_x'],
    positionY: json['position_y'],
    positionZ: json['position_z'],
  }
}

export function LineToJSON(value?: Line | null): any {
  if (value == null) {
    return value
  }
  return {
    position_x: value['positionX'],
    position_y: value['positionY'],
    position_z: value['positionZ'],
  }
}
