/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CarouselImageResponse } from './CarouselImageResponse'
import {
  CarouselImageResponseFromJSON,
  CarouselImageResponseFromJSONTyped,
  CarouselImageResponseToJSON,
} from './CarouselImageResponse'

/**
 *
 * @export
 * @interface ListCarouselImageResponse
 */
export interface ListCarouselImageResponse {
  /**
   * 符合查询条件的结果总数
   * @type {number}
   * @memberof ListCarouselImageResponse
   */
  totalCount: number
  /**
   *
   * @type {Array<CarouselImageResponse>}
   * @memberof ListCarouselImageResponse
   */
  data: Array<CarouselImageResponse>
}

/**
 * Check if a given object implements the ListCarouselImageResponse interface.
 */
export function instanceOfListCarouselImageResponse(value: object): boolean {
  if (!('totalCount' in value)) return false
  if (!('data' in value)) return false
  return true
}

export function ListCarouselImageResponseFromJSON(json: any): ListCarouselImageResponse {
  return ListCarouselImageResponseFromJSONTyped(json, false)
}

export function ListCarouselImageResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCarouselImageResponse {
  if (json == null) {
    return json
  }
  return {
    totalCount: json['totalCount'],
    data: (json['data'] as Array<any>).map(CarouselImageResponseFromJSON),
  }
}

export function ListCarouselImageResponseToJSON(value?: ListCarouselImageResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    totalCount: value['totalCount'],
    data: (value['data'] as Array<any>).map(CarouselImageResponseToJSON),
  }
}
