/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { SceneHistoryResponse } from './SceneHistoryResponse'
import {
  SceneHistoryResponseFromJSON,
  SceneHistoryResponseFromJSONTyped,
  SceneHistoryResponseToJSON,
} from './SceneHistoryResponse'

/**
 *
 * @export
 * @interface ListSceneHistroyResponse
 */
export interface ListSceneHistroyResponse {
  /**
   *
   * @type {number}
   * @memberof ListSceneHistroyResponse
   */
  totalCount: number
  /**
   *
   * @type {Array<SceneHistoryResponse>}
   * @memberof ListSceneHistroyResponse
   */
  data: Array<SceneHistoryResponse>
}

/**
 * Check if a given object implements the ListSceneHistroyResponse interface.
 */
export function instanceOfListSceneHistroyResponse(value: object): boolean {
  if (!('totalCount' in value)) return false
  if (!('data' in value)) return false
  return true
}

export function ListSceneHistroyResponseFromJSON(json: any): ListSceneHistroyResponse {
  return ListSceneHistroyResponseFromJSONTyped(json, false)
}

export function ListSceneHistroyResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListSceneHistroyResponse {
  if (json == null) {
    return json
  }
  return {
    totalCount: json['totalCount'],
    data: (json['data'] as Array<any>).map(SceneHistoryResponseFromJSON),
  }
}

export function ListSceneHistroyResponseToJSON(value?: ListSceneHistroyResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    totalCount: value['totalCount'],
    data: (value['data'] as Array<any>).map(SceneHistoryResponseToJSON),
  }
}
