/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AnnotationResponse } from './AnnotationResponse'
import {
  AnnotationResponseFromJSON,
  AnnotationResponseFromJSONTyped,
  AnnotationResponseToJSON,
} from './AnnotationResponse'

/**
 *
 * @export
 * @interface ListAnnotationResponse
 */
export interface ListAnnotationResponse {
  /**
   *
   * @type {number}
   * @memberof ListAnnotationResponse
   */
  totalCount: number
  /**
   *
   * @type {Array<AnnotationResponse>}
   * @memberof ListAnnotationResponse
   */
  data: Array<AnnotationResponse>
}

/**
 * Check if a given object implements the ListAnnotationResponse interface.
 */
export function instanceOfListAnnotationResponse(value: object): boolean {
  if (!('totalCount' in value)) return false
  if (!('data' in value)) return false
  return true
}

export function ListAnnotationResponseFromJSON(json: any): ListAnnotationResponse {
  return ListAnnotationResponseFromJSONTyped(json, false)
}

export function ListAnnotationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListAnnotationResponse {
  if (json == null) {
    return json
  }
  return {
    totalCount: json['totalCount'],
    data: (json['data'] as Array<any>).map(AnnotationResponseFromJSON),
  }
}

export function ListAnnotationResponseToJSON(value?: ListAnnotationResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    totalCount: value['totalCount'],
    data: (value['data'] as Array<any>).map(AnnotationResponseToJSON),
  }
}
