/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ListCarouselImage400Response
 */
export interface ListCarouselImage400Response {
  /**
   *
   * @type {string}
   * @memberof ListCarouselImage400Response
   */
  message: string
}

/**
 * Check if a given object implements the ListCarouselImage400Response interface.
 */
export function instanceOfListCarouselImage400Response(value: object): boolean {
  if (!('message' in value)) return false
  return true
}

export function ListCarouselImage400ResponseFromJSON(json: any): ListCarouselImage400Response {
  return ListCarouselImage400ResponseFromJSONTyped(json, false)
}

export function ListCarouselImage400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCarouselImage400Response {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function ListCarouselImage400ResponseToJSON(
  value?: ListCarouselImage400Response | null,
): any {
  if (value == null) {
    return value
  }
  return {
    message: value['message'],
  }
}
