/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetUserInfoResponse } from './GetUserInfoResponse'
import {
  GetUserInfoResponseFromJSON,
  GetUserInfoResponseFromJSONTyped,
  GetUserInfoResponseToJSON,
} from './GetUserInfoResponse'

/**
 *
 * @export
 * @interface ListUserInfoResponse
 */
export interface ListUserInfoResponse {
  /**
   *
   * @type {number}
   * @memberof ListUserInfoResponse
   */
  totalCount: number
  /**
   *
   * @type {Array<GetUserInfoResponse>}
   * @memberof ListUserInfoResponse
   */
  data: Array<GetUserInfoResponse>
}

/**
 * Check if a given object implements the ListUserInfoResponse interface.
 */
export function instanceOfListUserInfoResponse(value: object): boolean {
  if (!('totalCount' in value)) return false
  if (!('data' in value)) return false
  return true
}

export function ListUserInfoResponseFromJSON(json: any): ListUserInfoResponse {
  return ListUserInfoResponseFromJSONTyped(json, false)
}

export function ListUserInfoResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListUserInfoResponse {
  if (json == null) {
    return json
  }
  return {
    totalCount: json['totalCount'],
    data: (json['data'] as Array<any>).map(GetUserInfoResponseFromJSON),
  }
}

export function ListUserInfoResponseToJSON(value?: ListUserInfoResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    totalCount: value['totalCount'],
    data: (value['data'] as Array<any>).map(GetUserInfoResponseToJSON),
  }
}
