/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { SceneResponse } from './SceneResponse'
import {
  SceneResponseFromJSON,
  SceneResponseFromJSONTyped,
  SceneResponseToJSON,
} from './SceneResponse'

/**
 *
 * @export
 * @interface ListScenesResponse
 */
export interface ListScenesResponse {
  /**
   * 此符合此查询条件的结果总数（不止 `data` 里面的数据）
   * @type {number}
   * @memberof ListScenesResponse
   */
  totalCount: number
  /**
   * 场景列表
   * @type {Array<SceneResponse>}
   * @memberof ListScenesResponse
   */
  data: Array<SceneResponse>
}

/**
 * Check if a given object implements the ListScenesResponse interface.
 */
export function instanceOfListScenesResponse(value: object): boolean {
  if (!('totalCount' in value)) return false
  if (!('data' in value)) return false
  return true
}

export function ListScenesResponseFromJSON(json: any): ListScenesResponse {
  return ListScenesResponseFromJSONTyped(json, false)
}

export function ListScenesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListScenesResponse {
  if (json == null) {
    return json
  }
  return {
    totalCount: json['totalCount'],
    data: (json['data'] as Array<any>).map(SceneResponseFromJSON),
  }
}

export function ListScenesResponseToJSON(value?: ListScenesResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    totalCount: value['totalCount'],
    data: (value['data'] as Array<any>).map(SceneResponseToJSON),
  }
}
