/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ListCollaborators200Response
 */
export interface ListCollaborators200Response {
  /**
   * 直接返回数据库中存储的JSON字符串即可
   * @type {Array<number>}
   * @memberof ListCollaborators200Response
   */
  collaborators: Array<number>
}

/**
 * Check if a given object implements the ListCollaborators200Response interface.
 */
export function instanceOfListCollaborators200Response(value: object): boolean {
  if (!('collaborators' in value)) return false
  return true
}

export function ListCollaborators200ResponseFromJSON(json: any): ListCollaborators200Response {
  return ListCollaborators200ResponseFromJSONTyped(json, false)
}

export function ListCollaborators200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCollaborators200Response {
  if (json == null) {
    return json
  }
  return {
    collaborators: json['collaborators'],
  }
}

export function ListCollaborators200ResponseToJSON(
  value?: ListCollaborators200Response | null,
): any {
  if (value == null) {
    return value
  }
  return {
    collaborators: value['collaborators'],
  }
}
