/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
  /**
   * 用户需要保存此 token，在请求需要鉴权的接口时，把 token 携带在 Header 中。
   *
   * @example
   * ```ts
   * const token = ''
   * const headers = {
   *   'Authorization': `Bearer ${token}`
   * }
   * ```
   * @type {string}
   * @memberof LoginResponse
   */
  token: string
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): boolean {
  if (!('token' in value)) return false
  return true
}

export function LoginResponseFromJSON(json: any): LoginResponse {
  return LoginResponseFromJSONTyped(json, false)
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
  if (json == null) {
    return json
  }
  return {
    token: json['token'],
  }
}

export function LoginResponseToJSON(value?: LoginResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    token: value['token'],
  }
}
