/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
  /**
   * 用户名
   * @type {string}
   * @memberof LoginRequest
   */
  username: string
  /**
   * 密码
   * @type {string}
   * @memberof LoginRequest
   */
  password: string
}

/**
 * Check if a given object implements the LoginRequest interface.
 */
export function instanceOfLoginRequest(value: object): boolean {
  if (!('username' in value)) return false
  if (!('password' in value)) return false
  return true
}

export function LoginRequestFromJSON(json: any): LoginRequest {
  return LoginRequestFromJSONTyped(json, false)
}

export function LoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginRequest {
  if (json == null) {
    return json
  }
  return {
    username: json['username'],
    password: json['password'],
  }
}

export function LoginRequestToJSON(value?: LoginRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    username: value['username'],
    password: value['password'],
  }
}
