/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const OperationType = {
  Create: 'Create',
  Read: 'Read',
  Update: 'Update',
  Delete: 'Delete',
} as const
export type OperationType = (typeof OperationType)[keyof typeof OperationType]

export function instanceOfOperationType(value: any): boolean {
  return Object.values(OperationType).includes(value)
}

export function OperationTypeFromJSON(json: any): OperationType {
  return OperationTypeFromJSONTyped(json, false)
}

export function OperationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationType {
  return json as OperationType
}

export function OperationTypeToJSON(value?: OperationType | null): any {
  return value as any
}
