/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface OrderAnnotationRequest
 */
export interface OrderAnnotationRequest {
  /**
   *
   * @type {Array<number>}
   * @memberof OrderAnnotationRequest
   */
  orderList: Array<number>
}

/**
 * Check if a given object implements the OrderAnnotationRequest interface.
 */
export function instanceOfOrderAnnotationRequest(value: object): boolean {
  if (!('orderList' in value)) return false
  return true
}

export function OrderAnnotationRequestFromJSON(json: any): OrderAnnotationRequest {
  return OrderAnnotationRequestFromJSONTyped(json, false)
}

export function OrderAnnotationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrderAnnotationRequest {
  if (json == null) {
    return json
  }
  return {
    orderList: json['orderList'],
  }
}

export function OrderAnnotationRequestToJSON(value?: OrderAnnotationRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    orderList: value['orderList'],
  }
}
