/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
  /**
   * 用户名
   * @type {string}
   * @memberof RegisterRequest
   */
  username: string
  /**
   * 密码
   * @type {string}
   * @memberof RegisterRequest
   */
  password: string
}

/**
 * Check if a given object implements the RegisterRequest interface.
 */
export function instanceOfRegisterRequest(value: object): boolean {
  if (!('username' in value)) return false
  if (!('password' in value)) return false
  return true
}

export function RegisterRequestFromJSON(json: any): RegisterRequest {
  return RegisterRequestFromJSONTyped(json, false)
}

export function RegisterRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterRequest {
  if (json == null) {
    return json
  }
  return {
    username: json['username'],
    password: json['password'],
  }
}

export function RegisterRequestToJSON(value?: RegisterRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    username: value['username'],
    password: value['password'],
  }
}
