/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const SceneAuditStatus = {
  Approved: 'approved',
} as const
export type SceneAuditStatus = (typeof SceneAuditStatus)[keyof typeof SceneAuditStatus]

export function instanceOfSceneAuditStatus(value: any): boolean {
  return Object.values(SceneAuditStatus).includes(value)
}

export function SceneAuditStatusFromJSON(json: any): SceneAuditStatus {
  return SceneAuditStatusFromJSONTyped(json, false)
}

export function SceneAuditStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SceneAuditStatus {
  return json as SceneAuditStatus
}

export function SceneAuditStatusToJSON(value?: SceneAuditStatus | null): any {
  return value as any
}
