/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Vector3 } from './Vector3'
import { Vector3FromJSON, Vector3FromJSONTyped, Vector3ToJSON } from './Vector3'

/**
 *
 * @export
 * @interface SceneResponse
 */
export interface SceneResponse {
  /**
   * 场景 ID
   * @type {number}
   * @memberof SceneResponse
   */
  id: number
  /**
   * 场景创建者 ID
   * @type {number}
   * @memberof SceneResponse
   */
  creatorId: number
  /**
   * 创建时间，精确到毫秒的时间戳
   * @type {number}
   * @memberof SceneResponse
   */
  createTime: number
  /**
   * 场景名
   * @type {string}
   * @memberof SceneResponse
   */
  name: string
  /**
   * 场景的 Luma 链接，如 `https://lumalabs.ai/capture/8575c740-88ce-4418-bd06-de06c51b2f3f`
   * @type {string}
   * @memberof SceneResponse
   */
  url: string
  /**
   * 场景描述
   * @type {string}
   * @memberof SceneResponse
   */
  description: string
  /**
   * 场景是否公开可见
   * @type {boolean}
   * @memberof SceneResponse
   */
  isPublic: boolean
  /**
   * 审核状态，数据库使用tinyint实现，0未审核，1审核通过，2审核拒绝
   * @type {number}
   * @memberof SceneResponse
   */
  isAudit: number
  /**
   * 场景是否被删除
   * @type {boolean}
   * @memberof SceneResponse
   */
  isDeleted: boolean
  /**
   * 协助者id数组
   * @type {Array<number>}
   * @memberof SceneResponse
   */
  collaborators: Array<number>
  /**
   * 封面url
   * @type {string}
   * @memberof SceneResponse
   */
  coverUrl: string
  /**
   * 标签
   * @type {Array<string>}
   * @memberof SceneResponse
   */
  tags: Array<string>
  /**
   *
   * @type {Vector3}
   * @memberof SceneResponse
   */
  birthPosition?: Vector3
  /**
   *
   * @type {Vector3}
   * @memberof SceneResponse
   */
  birthRotation?: Vector3
}

/**
 * Check if a given object implements the SceneResponse interface.
 */
export function instanceOfSceneResponse(value: object): boolean {
  if (!('id' in value)) return false
  if (!('creatorId' in value)) return false
  if (!('createTime' in value)) return false
  if (!('name' in value)) return false
  if (!('url' in value)) return false
  if (!('description' in value)) return false
  if (!('isPublic' in value)) return false
  if (!('isAudit' in value)) return false
  if (!('isDeleted' in value)) return false
  if (!('collaborators' in value)) return false
  if (!('coverUrl' in value)) return false
  if (!('tags' in value)) return false
  return true
}

export function SceneResponseFromJSON(json: any): SceneResponse {
  return SceneResponseFromJSONTyped(json, false)
}

export function SceneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SceneResponse {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    creatorId: json['creatorId'],
    createTime: json['createTime'],
    name: json['name'],
    url: json['url'],
    description: json['description'],
    isPublic: json['isPublic'],
    isAudit: json['isAudit'],
    isDeleted: json['isDeleted'],
    collaborators: json['collaborators'],
    coverUrl: json['coverUrl'],
    tags: json['tags'],
    birthPosition:
      json['birthPosition'] == null ? undefined : Vector3FromJSON(json['birthPosition']),
    birthRotation:
      json['birthRotation'] == null ? undefined : Vector3FromJSON(json['birthRotation']),
  }
}

export function SceneResponseToJSON(value?: SceneResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value['id'],
    creatorId: value['creatorId'],
    createTime: value['createTime'],
    name: value['name'],
    url: value['url'],
    description: value['description'],
    isPublic: value['isPublic'],
    isAudit: value['isAudit'],
    isDeleted: value['isDeleted'],
    collaborators: value['collaborators'],
    coverUrl: value['coverUrl'],
    tags: value['tags'],
    birthPosition: Vector3ToJSON(value['birthPosition']),
    birthRotation: Vector3ToJSON(value['birthRotation']),
  }
}
