/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SceneHistoryResponse
 */
export interface SceneHistoryResponse {
  /**
   * ID 编号
   * @type {number}
   * @memberof SceneHistoryResponse
   */
  id: number
  /**
   *
   * @type {number}
   * @memberof SceneHistoryResponse
   */
  sceneId: number
  /**
   *
   * @type {number}
   * @memberof SceneHistoryResponse
   */
  userId: number
  /**
   * 访问时间
   * @type {number}
   * @memberof SceneHistoryResponse
   */
  time: number
}

/**
 * Check if a given object implements the SceneHistoryResponse interface.
 */
export function instanceOfSceneHistoryResponse(value: object): boolean {
  if (!('id' in value)) return false
  if (!('sceneId' in value)) return false
  if (!('userId' in value)) return false
  if (!('time' in value)) return false
  return true
}

export function SceneHistoryResponseFromJSON(json: any): SceneHistoryResponse {
  return SceneHistoryResponseFromJSONTyped(json, false)
}

export function SceneHistoryResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SceneHistoryResponse {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    sceneId: json['sceneId'],
    userId: json['userId'],
    time: json['time'],
  }
}

export function SceneHistoryResponseToJSON(value?: SceneHistoryResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value['id'],
    sceneId: value['sceneId'],
    userId: value['userId'],
    time: value['time'],
  }
}
