/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TagId
 */
export interface TagId {
  /**
   * id，ID 编号
   * @type {number}
   * @memberof TagId
   */
  id: number
}

/**
 * Check if a given object implements the TagId interface.
 */
export function instanceOfTagId(value: object): boolean {
  if (!('id' in value)) return false
  return true
}

export function TagIdFromJSON(json: any): TagId {
  return TagIdFromJSONTyped(json, false)
}

export function TagIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagId {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
  }
}

export function TagIdToJSON(value?: TagId | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value['id'],
  }
}
