/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TagListRequest
 */
export interface TagListRequest {
  /**
   * 标签
   * @type {Array<string>}
   * @memberof TagListRequest
   */
  tags: Array<string>
}

/**
 * Check if a given object implements the TagListRequest interface.
 */
export function instanceOfTagListRequest(value: object): boolean {
  if (!('tags' in value)) return false
  return true
}

export function TagListRequestFromJSON(json: any): TagListRequest {
  return TagListRequestFromJSONTyped(json, false)
}

export function TagListRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TagListRequest {
  if (json == null) {
    return json
  }
  return {
    tags: json['tags'],
  }
}

export function TagListRequestToJSON(value?: TagListRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    tags: value['tags'],
  }
}
