/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { TagsModel } from './TagsModel'
import { TagsModelFromJSON, TagsModelFromJSONTyped, TagsModelToJSON } from './TagsModel'

/**
 *
 * @export
 * @interface TagListResponse
 */
export interface TagListResponse {
  /**
   * ID 编号
   * @type {Array<TagsModel>}
   * @memberof TagListResponse
   */
  tagsList: Array<TagsModel>
}

/**
 * Check if a given object implements the TagListResponse interface.
 */
export function instanceOfTagListResponse(value: object): boolean {
  if (!('tagsList' in value)) return false
  return true
}

export function TagListResponseFromJSON(json: any): TagListResponse {
  return TagListResponseFromJSONTyped(json, false)
}

export function TagListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TagListResponse {
  if (json == null) {
    return json
  }
  return {
    tagsList: (json['tagsList'] as Array<any>).map(TagsModelFromJSON),
  }
}

export function TagListResponseToJSON(value?: TagListResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    tagsList: (value['tagsList'] as Array<any>).map(TagsModelToJSON),
  }
}
