/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TagsModel
 */
export interface TagsModel {
  /**
   * id
   * @type {number}
   * @memberof TagsModel
   */
  tagId: number
  /**
   * tag名字
   * @type {string}
   * @memberof TagsModel
   */
  tagName: string
}

/**
 * Check if a given object implements the TagsModel interface.
 */
export function instanceOfTagsModel(value: object): boolean {
  if (!('tagId' in value)) return false
  if (!('tagName' in value)) return false
  return true
}

export function TagsModelFromJSON(json: any): TagsModel {
  return TagsModelFromJSONTyped(json, false)
}

export function TagsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagsModel {
  if (json == null) {
    return json
  }
  return {
    tagId: json['tagId'],
    tagName: json['tagName'],
  }
}

export function TagsModelToJSON(value?: TagsModel | null): any {
  if (value == null) {
    return value
  }
  return {
    tagId: value['tagId'],
    tagName: value['tagName'],
  }
}
