/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TagsFindRequest
 */
export interface TagsFindRequest {
  /**
   * 标签名，名称
   * @type {string}
   * @memberof TagsFindRequest
   */
  tagName: string
}

/**
 * Check if a given object implements the TagsFindRequest interface.
 */
export function instanceOfTagsFindRequest(value: object): boolean {
  if (!('tagName' in value)) return false
  return true
}

export function TagsFindRequestFromJSON(json: any): TagsFindRequest {
  return TagsFindRequestFromJSONTyped(json, false)
}

export function TagsFindRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TagsFindRequest {
  if (json == null) {
    return json
  }
  return {
    tagName: json['tagName'],
  }
}

export function TagsFindRequestToJSON(value?: TagsFindRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    tagName: value['tagName'],
  }
}
