/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TopSceneId
 */
export interface TopSceneId {
  /**
   * 场景id
   * @type {number}
   * @memberof TopSceneId
   */
  id: number
}

/**
 * Check if a given object implements the TopSceneId interface.
 */
export function instanceOfTopSceneId(value: object): boolean {
  if (!('id' in value)) return false
  return true
}

export function TopSceneIdFromJSON(json: any): TopSceneId {
  return TopSceneIdFromJSONTyped(json, false)
}

export function TopSceneIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopSceneId {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
  }
}

export function TopSceneIdToJSON(value?: TopSceneId | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value['id'],
  }
}
