/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdatePasswordRequest
 */
export interface UpdatePasswordRequest {
  /**
   * 原密码
   * @type {string}
   * @memberof UpdatePasswordRequest
   */
  oldPassword: string
  /**
   * 新密码
   * @type {string}
   * @memberof UpdatePasswordRequest
   */
  newPassword: string
}

/**
 * Check if a given object implements the UpdatePasswordRequest interface.
 */
export function instanceOfUpdatePasswordRequest(value: object): boolean {
  if (!('oldPassword' in value)) return false
  if (!('newPassword' in value)) return false
  return true
}

export function UpdatePasswordRequestFromJSON(json: any): UpdatePasswordRequest {
  return UpdatePasswordRequestFromJSONTyped(json, false)
}

export function UpdatePasswordRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePasswordRequest {
  if (json == null) {
    return json
  }
  return {
    oldPassword: json['oldPassword'],
    newPassword: json['newPassword'],
  }
}

export function UpdatePasswordRequestToJSON(value?: UpdatePasswordRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    oldPassword: value['oldPassword'],
    newPassword: value['newPassword'],
  }
}
