/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { TopSceneId } from './TopSceneId'
import { TopSceneIdFromJSON, TopSceneIdFromJSONTyped, TopSceneIdToJSON } from './TopSceneId'

/**
 *
 * @export
 * @interface UpdateUserInfoRequest
 */
export interface UpdateUserInfoRequest {
  /**
   * 用户名称
   * @type {string}
   * @memberof UpdateUserInfoRequest
   */
  name?: string
  /**
   * 头像url
   * @type {string}
   * @memberof UpdateUserInfoRequest
   */
  avatarUrl?: string
  /**
   * 昵称
   * @type {string}
   * @memberof UpdateUserInfoRequest
   */
  nickName?: string
  /**
   * 签名
   * @type {string}
   * @memberof UpdateUserInfoRequest
   */
  motto?: string
  /**
   * 性别
   * @type {string}
   * @memberof UpdateUserInfoRequest
   */
  gender?: UpdateUserInfoRequestGenderV4Compat
  /**
   * 生日
   * @type {string}
   * @memberof UpdateUserInfoRequest
   */
  birthday?: string
  /**
   * 地址
   * @type {string}
   * @memberof UpdateUserInfoRequest
   */
  address?: string
  /**
   * 置顶场景id列表，不能超过3个
   * @type {Array<TopSceneId>}
   * @memberof UpdateUserInfoRequest
   */
  topSceneIdList?: Array<TopSceneId>
}

/**
 * @export
 */
export const UpdateUserInfoRequestGenderV4Compat = {
  Male: 'male',
  Female: 'female',
  Unkown: 'unkown',
} as const
export type UpdateUserInfoRequestGenderV4Compat =
  (typeof UpdateUserInfoRequestGenderV4Compat)[keyof typeof UpdateUserInfoRequestGenderV4Compat]

/**
 * Check if a given object implements the UpdateUserInfoRequest interface.
 */
export function instanceOfUpdateUserInfoRequest(value: object): boolean {
  return true
}

export function UpdateUserInfoRequestFromJSON(json: any): UpdateUserInfoRequest {
  return UpdateUserInfoRequestFromJSONTyped(json, false)
}

export function UpdateUserInfoRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserInfoRequest {
  if (json == null) {
    return json
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    avatarUrl: json['avatarUrl'] == null ? undefined : json['avatarUrl'],
    nickName: json['nickName'] == null ? undefined : json['nickName'],
    motto: json['motto'] == null ? undefined : json['motto'],
    gender: json['gender'] == null ? undefined : json['gender'],
    birthday: json['birthday'] == null ? undefined : json['birthday'],
    address: json['address'] == null ? undefined : json['address'],
    topSceneIdList:
      json['topSceneIdList'] == null
        ? undefined
        : (json['topSceneIdList'] as Array<any>).map(TopSceneIdFromJSON),
  }
}

export function UpdateUserInfoRequestToJSON(value?: UpdateUserInfoRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    name: value['name'],
    avatarUrl: value['avatarUrl'],
    nickName: value['nickName'],
    motto: value['motto'],
    gender: value['gender'],
    birthday: value['birthday'],
    address: value['address'],
    topSceneIdList:
      value['topSceneIdList'] == null
        ? undefined
        : (value['topSceneIdList'] as Array<any>).map(TopSceneIdToJSON),
  }
}
