/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdatePassword200Response
 */
export interface UpdatePassword200Response {
  /**
   * token
   * @type {string}
   * @memberof UpdatePassword200Response
   */
  token: string
  /**
   * 用户id
   * @type {number}
   * @memberof UpdatePassword200Response
   */
  userId: number
  /**
   * 名字
   * @type {string}
   * @memberof UpdatePassword200Response
   */
  userName: string
}

/**
 * Check if a given object implements the UpdatePassword200Response interface.
 */
export function instanceOfUpdatePassword200Response(value: object): boolean {
  if (!('token' in value)) return false
  if (!('userId' in value)) return false
  if (!('userName' in value)) return false
  return true
}

export function UpdatePassword200ResponseFromJSON(json: any): UpdatePassword200Response {
  return UpdatePassword200ResponseFromJSONTyped(json, false)
}

export function UpdatePassword200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePassword200Response {
  if (json == null) {
    return json
  }
  return {
    token: json['token'],
    userId: json['userId'],
    userName: json['userName'],
  }
}

export function UpdatePassword200ResponseToJSON(value?: UpdatePassword200Response | null): any {
  if (value == null) {
    return value
  }
  return {
    token: value['token'],
    userId: value['userId'],
    userName: value['userName'],
  }
}
