/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdatePasswordResponse
 */
export interface UpdatePasswordResponse {
  /**
   * token
   * @type {string}
   * @memberof UpdatePasswordResponse
   */
  token: string
  /**
   * 用户id
   * @type {number}
   * @memberof UpdatePasswordResponse
   */
  userId: number
  /**
   * 名字
   * @type {string}
   * @memberof UpdatePasswordResponse
   */
  userName: string
}

/**
 * Check if a given object implements the UpdatePasswordResponse interface.
 */
export function instanceOfUpdatePasswordResponse(value: object): boolean {
  if (!('token' in value)) return false
  if (!('userId' in value)) return false
  if (!('userName' in value)) return false
  return true
}

export function UpdatePasswordResponseFromJSON(json: any): UpdatePasswordResponse {
  return UpdatePasswordResponseFromJSONTyped(json, false)
}

export function UpdatePasswordResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePasswordResponse {
  if (json == null) {
    return json
  }
  return {
    token: json['token'],
    userId: json['userId'],
    userName: json['userName'],
  }
}

export function UpdatePasswordResponseToJSON(value?: UpdatePasswordResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    token: value['token'],
    userId: value['userId'],
    userName: value['userName'],
  }
}
