/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { TopSceneId } from './TopSceneId'
import { TopSceneIdFromJSON, TopSceneIdFromJSONTyped, TopSceneIdToJSON } from './TopSceneId'

/**
 *
 * @export
 * @interface UpdateUserInfoResponse
 */
export interface UpdateUserInfoResponse {
  /**
   * 用户名，名称
   * @type {string}
   * @memberof UpdateUserInfoResponse
   */
  name?: string
  /**
   * 头像链接
   * @type {string}
   * @memberof UpdateUserInfoResponse
   */
  avaterUrl?: string
  /**
   * 昵称
   * @type {string}
   * @memberof UpdateUserInfoResponse
   */
  nickName?: string
  /**
   * 签名
   * @type {string}
   * @memberof UpdateUserInfoResponse
   */
  motto?: string
  /**
   * 性别
   * @type {string}
   * @memberof UpdateUserInfoResponse
   */
  gender?: UpdateUserInfoResponseGenderV4Compat
  /**
   * 生日
   * @type {string}
   * @memberof UpdateUserInfoResponse
   */
  birthday?: string
  /**
   * 地址
   * @type {string}
   * @memberof UpdateUserInfoResponse
   */
  address?: string
  /**
   * 置顶场景id列表，不能超过3个
   * @type {Array<TopSceneId>}
   * @memberof UpdateUserInfoResponse
   */
  topSceneIdList?: Array<TopSceneId>
}

/**
 * @export
 */
export const UpdateUserInfoResponseGenderV4Compat = {
  Male: 'male',
  Female: 'female',
  Unkown: 'unkown',
} as const
export type UpdateUserInfoResponseGenderV4Compat =
  (typeof UpdateUserInfoResponseGenderV4Compat)[keyof typeof UpdateUserInfoResponseGenderV4Compat]

/**
 * Check if a given object implements the UpdateUserInfoResponse interface.
 */
export function instanceOfUpdateUserInfoResponse(value: object): boolean {
  return true
}

export function UpdateUserInfoResponseFromJSON(json: any): UpdateUserInfoResponse {
  return UpdateUserInfoResponseFromJSONTyped(json, false)
}

export function UpdateUserInfoResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserInfoResponse {
  if (json == null) {
    return json
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    avaterUrl: json['avaterUrl'] == null ? undefined : json['avaterUrl'],
    nickName: json['nick_name'] == null ? undefined : json['nick_name'],
    motto: json['motto'] == null ? undefined : json['motto'],
    gender: json['gender'] == null ? undefined : json['gender'],
    birthday: json['birthday'] == null ? undefined : json['birthday'],
    address: json['address'] == null ? undefined : json['address'],
    topSceneIdList:
      json['topSceneIdList'] == null
        ? undefined
        : (json['topSceneIdList'] as Array<any>).map(TopSceneIdFromJSON),
  }
}

export function UpdateUserInfoResponseToJSON(value?: UpdateUserInfoResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    name: value['name'],
    avaterUrl: value['avaterUrl'],
    nick_name: value['nickName'],
    motto: value['motto'],
    gender: value['gender'],
    birthday: value['birthday'],
    address: value['address'],
    topSceneIdList:
      value['topSceneIdList'] == null
        ? undefined
        : (value['topSceneIdList'] as Array<any>).map(TopSceneIdToJSON),
  }
}
