/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UploadCover400Response
 */
export interface UploadCover400Response {
  /**
   *
   * @type {string}
   * @memberof UploadCover400Response
   */
  message: string
}

/**
 * Check if a given object implements the UploadCover400Response interface.
 */
export function instanceOfUploadCover400Response(value: object): boolean {
  if (!('message' in value)) return false
  return true
}

export function UploadCover400ResponseFromJSON(json: any): UploadCover400Response {
  return UploadCover400ResponseFromJSONTyped(json, false)
}

export function UploadCover400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UploadCover400Response {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function UploadCover400ResponseToJSON(value?: UploadCover400Response | null): any {
  if (value == null) {
    return value
  }
  return {
    message: value['message'],
  }
}
