/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UploadImageResponse
 */
export interface UploadImageResponse {
  /**
   * 图片url，上传好的图片链接
   * @type {string}
   * @memberof UploadImageResponse
   */
  imageUrl: string
}

/**
 * Check if a given object implements the UploadImageResponse interface.
 */
export function instanceOfUploadImageResponse(value: object): boolean {
  if (!('imageUrl' in value)) return false
  return true
}

export function UploadImageResponseFromJSON(json: any): UploadImageResponse {
  return UploadImageResponseFromJSONTyped(json, false)
}

export function UploadImageResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UploadImageResponse {
  if (json == null) {
    return json
  }
  return {
    imageUrl: json['imageUrl'],
  }
}

export function UploadImageResponseToJSON(value?: UploadImageResponse | null): any {
  if (value == null) {
    return value
  }
  return {
    imageUrl: value['imageUrl'],
  }
}
