/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { UploadImageType } from './UploadImageType'
import {
  UploadImageTypeFromJSON,
  UploadImageTypeFromJSONTyped,
  UploadImageTypeToJSON,
} from './UploadImageType'

/**
 *
 * @export
 * @interface UploadImageRequest
 */
export interface UploadImageRequest {
  /**
   * 图片的 Base64 字符串
   * @type {string}
   * @memberof UploadImageRequest
   */
  image: string
  /**
   *
   * @type {UploadImageType}
   * @memberof UploadImageRequest
   */
  type: UploadImageType
  /**
   * 当type为sceneCover时
   * @type {number}
   * @memberof UploadImageRequest
   */
  sceneId?: number
}

/**
 * Check if a given object implements the UploadImageRequest interface.
 */
export function instanceOfUploadImageRequest(value: object): boolean {
  if (!('image' in value)) return false
  if (!('type' in value)) return false
  return true
}

export function UploadImageRequestFromJSON(json: any): UploadImageRequest {
  return UploadImageRequestFromJSONTyped(json, false)
}

export function UploadImageRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UploadImageRequest {
  if (json == null) {
    return json
  }
  return {
    image: json['image'],
    type: UploadImageTypeFromJSON(json['type']),
    sceneId: json['sceneId'] == null ? undefined : json['sceneId'],
  }
}

export function UploadImageRequestToJSON(value?: UploadImageRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    image: value['image'],
    type: UploadImageTypeToJSON(value['type']),
    sceneId: value['sceneId'],
  }
}
