/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UploadCoverRequest
 */
export interface UploadCoverRequest {
  /**
   * base64编码格式的图片
   * @type {string}
   * @memberof UploadCoverRequest
   */
  image: string
  /**
   *
   * @type {number}
   * @memberof UploadCoverRequest
   */
  sceneId: number
}

/**
 * Check if a given object implements the UploadCoverRequest interface.
 */
export function instanceOfUploadCoverRequest(value: object): boolean {
  if (!('image' in value)) return false
  if (!('sceneId' in value)) return false
  return true
}

export function UploadCoverRequestFromJSON(json: any): UploadCoverRequest {
  return UploadCoverRequestFromJSONTyped(json, false)
}

export function UploadCoverRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UploadCoverRequest {
  if (json == null) {
    return json
  }
  return {
    image: json['image'],
    sceneId: json['sceneId'],
  }
}

export function UploadCoverRequestToJSON(value?: UploadCoverRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    image: value['image'],
    sceneId: value['sceneId'],
  }
}
