/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const UploadImageType = {
  Avatar: 'avatar',
  SceneCover: 'sceneCover',
  Introduction: 'introduction',
} as const
export type UploadImageType = (typeof UploadImageType)[keyof typeof UploadImageType]

export function instanceOfUploadImageType(value: any): boolean {
  return Object.values(UploadImageType).includes(value)
}

export function UploadImageTypeFromJSON(json: any): UploadImageType {
  return UploadImageTypeFromJSONTyped(json, false)
}

export function UploadImageTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UploadImageType {
  return json as UploadImageType
}

export function UploadImageTypeToJSON(value?: UploadImageType | null): any {
  return value as any
}
