/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UploadVideo200Response
 */
export interface UploadVideo200Response {
  /**
   * 返还视频url，通常应该是cacheUrl
   * @type {string}
   * @memberof UploadVideo200Response
   */
  videoUrl: string
}

/**
 * Check if a given object implements the UploadVideo200Response interface.
 */
export function instanceOfUploadVideo200Response(value: object): boolean {
  if (!('videoUrl' in value)) return false
  return true
}

export function UploadVideo200ResponseFromJSON(json: any): UploadVideo200Response {
  return UploadVideo200ResponseFromJSONTyped(json, false)
}

export function UploadVideo200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UploadVideo200Response {
  if (json == null) {
    return json
  }
  return {
    videoUrl: json['videoUrl'],
  }
}

export function UploadVideo200ResponseToJSON(value?: UploadVideo200Response | null): any {
  if (value == null) {
    return value
  }
  return {
    videoUrl: value['videoUrl'],
  }
}
