/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UploadAudio200Response
 */
export interface UploadAudio200Response {
  /**
   * 返还音频url，通常应该是cacheUrl
   * @type {string}
   * @memberof UploadAudio200Response
   */
  audioUrl: string
}

/**
 * Check if a given object implements the UploadAudio200Response interface.
 */
export function instanceOfUploadAudio200Response(value: object): boolean {
  if (!('audioUrl' in value)) return false
  return true
}

export function UploadAudio200ResponseFromJSON(json: any): UploadAudio200Response {
  return UploadAudio200ResponseFromJSONTyped(json, false)
}

export function UploadAudio200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UploadAudio200Response {
  if (json == null) {
    return json
  }
  return {
    audioUrl: json['audioUrl'],
  }
}

export function UploadAudio200ResponseToJSON(value?: UploadAudio200Response | null): any {
  if (value == null) {
    return value
  }
  return {
    audioUrl: value['audioUrl'],
  }
}
