/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UploadIntroductionImage200Response
 */
export interface UploadIntroductionImage200Response {
  /**
   *
   * @type {string}
   * @memberof UploadIntroductionImage200Response
   */
  imageUrl: string
}

/**
 * Check if a given object implements the UploadIntroductionImage200Response interface.
 */
export function instanceOfUploadIntroductionImage200Response(value: object): boolean {
  if (!('imageUrl' in value)) return false
  return true
}

export function UploadIntroductionImage200ResponseFromJSON(
  json: any,
): UploadIntroductionImage200Response {
  return UploadIntroductionImage200ResponseFromJSONTyped(json, false)
}

export function UploadIntroductionImage200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UploadIntroductionImage200Response {
  if (json == null) {
    return json
  }
  return {
    imageUrl: json['imageUrl'],
  }
}

export function UploadIntroductionImage200ResponseToJSON(
  value?: UploadIntroductionImage200Response | null,
): any {
  if (value == null) {
    return value
  }
  return {
    imageUrl: value['imageUrl'],
  }
}
