/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Vector3
 */
export interface Vector3 {
  /**
   *
   * @type {number}
   * @memberof Vector3
   */
  x: number
  /**
   *
   * @type {number}
   * @memberof Vector3
   */
  y: number
  /**
   *
   * @type {number}
   * @memberof Vector3
   */
  z: number
}

/**
 * Check if a given object implements the Vector3 interface.
 */
export function instanceOfVector3(value: object): boolean {
  if (!('x' in value)) return false
  if (!('y' in value)) return false
  if (!('z' in value)) return false
  return true
}

export function Vector3FromJSON(json: any): Vector3 {
  return Vector3FromJSONTyped(json, false)
}

export function Vector3FromJSONTyped(json: any, ignoreDiscriminator: boolean): Vector3 {
  if (json == null) {
    return json
  }
  return {
    x: json['x'],
    y: json['y'],
    z: json['z'],
  }
}

export function Vector3ToJSON(value?: Vector3 | null): any {
  if (value == null) {
    return value
  }
  return {
    x: value['x'],
    y: value['y'],
    z: value['z'],
  }
}
